### ISSUE TITLE
singular .handler property?

### ISSUE THREAD

**Issue by dherman** [estree/estree#1]
Back in 2012 I suggested a backwards-incompatible [tweak to the TryStatement API](https://bugzilla.mozilla.org/show_bug.cgi?id=742612) to have a `handler` property instead of `handlers`, and it looks like [Esprima's change didn't match it](https://github.com/ariya/esprima/commit/78acf7af9c1). So now SpiderMonkey and Esprima do not behave compatibly for TryStatements.

The change would have been a more reasonable API but is it way too late for implementations to change to match it?

If we can't change implementations, then the spec should have `handlers` instead of `handler` and I'll file a SpiderMonkey bug to match that behavior.

**Comment by sebmck** [comment]
Related: jquery/esprima#187 https://code.google.com/p/esprima/issues/detail?id=433

**Comment by dherman** [comment]
Thanks! From those conversations it looks like it's unlikely anyone is willing to break compatibility on this, but it'd be nice to hear confirmation before closing the question definitively.

**Comment by mikesherov** [comment]
Esprima is going to change to `handler` in our next major build.

**Comment by dherman** [comment]
Great news!

**Comment by mikesherov** [comment]
@sebmck acorn already does handler?

**Comment by sebmck** [comment]
@mikesherov Yep

**Comment by mikesherov** [comment]
Sounds like we can close this and say `handler` it stays! @dherman close if you're satisfied. Perhaps we should add an errata section or add `handlers` to deprecated if it isn't already?

**Comment by mikesherov** [comment]
Ah actually, someone needs to PR this change. @dherman I choose you!

**Comment by ariya** [comment]
@dherman Are we keeping the empty `guardedHandlers` for now?

**Comment by dherman** [comment]
@ariya I filed this in issue #24.
