### ISSUE TITLE
SuperClass should be optional

### ISSUE THREAD

**Issue by lhorie** [estree/estree#101]
Currently es6.md has:

```
interface Class <: Node {
    id: Identifier | null;
    superClass: Expression;
    body: ClassBody;
}
```

Shouldn't it be `superClass: Expression | null`?

**Comment by sebmck** [comment]
Yep. Want to submit a PR?

**Comment by sebmck** [comment]
Closed via 16a657f17a514c50abea5a9d64a4a057927a60c5. Thanks @lhorie!

**Comment by lhorie** [comment]
Thanks @sebmck :)

**Comment by mikesherov** [comment]
That was fast :-)
