### ISSUE TITLE
Syntax (error) test suite?

### ISSUE THREAD

**Issue by sideshowbarker** [estree/estree#112]
I’m wondering if there’s some common set of tests available anywhere that is intended to test behavior of UAs with regard to syntax errors; in particular, error-reporting behavior.

A simple example is the case "`var;`", which in Firefox devtools will cause the message "`SyntaxError: missing variable name`" to be reported, while in Chrome devtools it causes the message "`SyntaxError: Unexpected token ;`" to be reported.

**Comment by RReverser** [comment]
Error messages (if any) are completely custom and up to implementor.

**Comment by sideshowbarker** [comment]
> Error messages (if any) are completely custom and up to implementor.

I understand that. I wasn’t suggesting a test suite that tested for exact error messages (or the necessarily tested for any error messages at all) but instead simply a set of tests that are known to have certain types of syntax errors (and so are expected to fail).

So while such a set of tests might not be very useful for testing interoperability, one thing that it could be useful for is in comparing the error-reporting behavior of different implementations—for example, the case I mentioned in the description for this issue, where the (more specific) error message reported by Firefox seems more useful to authors than the (less specific) one reported by Chrome.

**Comment by RReverser** [comment]
> simply a set of tests that are known to have certain types of syntax errors (and so are expected to fail)

Ah, then you can take tests from any parser out there (Acorn, Esprima, ...). As for the interoperability - duplicate of #55.

**Comment by sideshowbarker** [comment]
> Ah, then you can take tests from any parser out there (Acorn, Esprima, ...). As for the interoperability - duplicate of #55.

Cool, Thanks! (I’ve subscribed to that issue now)

**Comment by michaelficarra** [comment]
FYI, @shapesecurity will begin working on the enhancements to test-262 mentioned in that thread (parser pass/fail tests and early error tests) in a month or two.

**Comment by sideshowbarker** [comment]
> FYI, @shapesecurity will begin working on the enhancements to test-262 mentioned in that thread (parser pass/fail tests and early error tests) in a month or two.

Thanks—good to know. I did look through test-262 recently but hadn’t come across anything like that, so it’s good to know it’s in the works.
