### ISSUE TITLE
Allow patterns in left-hand side of for-in and for-of loops

### ISSUE THREAD

**Issue by zjmiller** [estree/estree#114]
Not sure what happened to 09beb49b20500393d33d766abdb60c0fd1ea9b2e, but the current ESTree spec doesn't allow destructuring patterns in the left-hand side of for-in or for-of loops.

**Comment by RReverser** [comment]
That's weird... I don't even see it among the `spec.md` commits.

**Comment by RReverser** [comment]
Probably someone did `push -f` :(
