### ISSUE TITLE
Proposal for open-ended type annotations

### ISSUE THREAD

**Issue by nzakas** [estree/estree#115]
With things like TypeScript and Flow becoming more popular, I'd really like to find a way to incorporate type annotations into ESTree in some sort of common way so we can start creating tooling around it. In particular, we're getting more requests in ESLint to be able to write rules around type annotations, but without having this is information in a predictable place, it's really hard to do that effectively.

I've thrown together a strawman below based on looking at what the TypeScript compiler produces and what Babel currently produces (neither works directly for ESTree, IMHO). I'm not tied to any of this, just want to start the conversation.

**Note:** What I'm proposing here is not necessarily TypeScript or Flow extensions to ESTree, just extensions that allow for type annotations. None of this relates to defining types, interfaces, etc.

## TypeAnnotation

First, suppose there's an abstract interface called `TypeAnnotation` from which TypeScript and Flow types can inherit as needed:

```js
interface TypeAnnotation <: Node {}
```

This is really just a placeholder in the ESTree format.

## TypedPattern

It's a little bit tricky to handle named function arguments with a type, such as `function x(a:string)` because we use `Identifier` (or `AssignmentPattern` for params with defaults). It doesn't seem correct to add something to `Identifier`, as identifiers don't generally have type annotations, and that also wouldn't handle the other cases. So, I think the easiest thing to do is to introduce a new node that represents a name-type pair.

```js
interface TypedPattern <: Pattern {
    id: Identifier;
    dataType: TypeAnnotation;
}
```

So in the case of `function x(a:string)`, the argument would be represented by a `TypedPattern` node. When there's a default value, such as `function x(a:string="")`, then the argument is an `AssignmentPattern` whose `left` property is a `TypedPattern`. 

There would be no need to extend the interface of `FunctionDeclaration`, `FunctionExpression`, or `ArrowFunctionExpression` since all of these use `Pattern` to define their parameters.

## Functions

In order to support a return value for functions (for example `function x(a:string):string {}`), we do need to extend the various function nodes:

```js
extend interface FunctionDeclaration {
    returnType: TypeAnnotation | null;
}

extend interface FunctionExpression {
    returnType: TypeAnnotation | null;
}

extend interface ArrowFunctionExpression {
    returnType: TypeAnnotation | null;
}
```

## VariableDeclarator

To support variable declarations, such as `var foo:string = "bar"`, we can simply used a `TypedPattern` in as the `VariableDeclarator`'s `id` property. The `id` property is already defined as `Pattern`, so no change to the `VariableDeclarator` interface is necessary.

## Conclusion

I think there's a fairly lightweight way to support type annotations formally in ESTree without typing us down to a particular flavor. As I said, I'm not typed to this proposal, I'd really just like to get some consensus as I think it could improve the state of typed-JavaScript tooling going forward.

**Comment by RReverser** [comment]
Well, Flow already has AST that extends ESTree, you can find it's definitions, for example, here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/estree/flow.d.ts. Can't we just use it?

**Comment by nzakas** [comment]
Can you give an overview of how it handles the situations I mention?

**Comment by RReverser** [comment]
Hm, apart from structural differences I don't really see the situations which it doesn't cover, can you please provide an example?
If it's just structural difference, personally I'd prefer to stick to the format that can be already produced / consumed by existing tooling (Flow, Babel, recast) rather than rewrite.
/cc @jeffmo

**Comment by jeffmo** [comment]
I'm in the middle of a few things at the moment so can't really respond in detail -- but figured I'd toss in that you can inspect Flow's ESTree-variant ast with `flow ast --pretty < code.js`.

I'll try to remember to come back to this after I'm back at a computer and see if I can offer any help

**Comment by nzakas** [comment]
@RReverser what I'm asking is for you to explain how Flow represents the instances I described so all the data is represented on this issue. I don't know how to read the file you referenced, so some narrative explanation would be helpful. It would also be helpful if you could point out how what I proposed is similar or different from what Flow is doing.

**Comment by RReverser** [comment]
@nzakas 

> what I'm asking is for you to explain how Flow represents the instances I described so all the data is represented on this issue

Sorry, it takes time to collect and post all the possible codes and their AST representations here, I believe that's what tools are for, not humans :smile: 

So, one options is what @jeffmo said above - you can see AST representation for each code using Flow's native tool.

Alternatively, you can see Flow-compliant representations in ASTExplorer - I tried to collect few examples that you posted for the convenience: http://astexplorer.net/#/MOQCM04yiH

> I don't know how to read the file you referenced

That file is just TypeScript definitions (same syntax that we're discussing here) of ESTree AST extensions.

**Comment by nzakas** [comment]
Sorry, I was really just asking for the Flow equivalent of the node definitions like I provided. It would be helpful if someone familiar with Flow could do that, because it would make comparison a lot easier and I wouldn't be left to interpret code I'm unfamiliar with to see if I can do so (the best I can tell, functions have `returnType`, but that's about all I can figure out). Also, I'm on Windows, so I can't run Flow myself.

I looked at ASTExplorer - the examples you shared all seem to place `typeAnnotation` directly on `Identifier`, which doesn't seem to be inline with the definitions in the file you shared (also seems incorrect semantically).

@ariya @mikesherov do you have thoughts on this?

**Comment by jeffmo** [comment]
Here's a run of `flow ast` over a file "code.js" for some of the common cases:

https://gist.github.com/jeffmo/f36bc249e41a46738805

**Comment by jeffmo** [comment]
When experimenting with different options in esprima-fb in the past, I found that wrapping typed identifiers in a wrapper node was a bit tedious for anyone that had certain expectations about which node they'd find in an identifier position -- whereas adding an expando property to the existing Identifer node signature was least intrusive to any existing users.

For example: Generic visitors that search the tree for `type: "Identifier"`. Generic visitors that were truly generic worked well -- they'd just mindlessly dive into this new "TypedIdentifier" node with a tester function. But any visitors that explicitly visit particular properties of particular nodes would do something explicitly different depending on `type` (which just means a new/unexpected node-type wouldn't be covered)

**Comment by nzakas** [comment]
Thanks, that's useful!

I can definitely see where just adding a new property to `Identifier` made sense in esprima-fb. IIRC, we hadn't yet agreed on how to represent default values for parameters at that point (can't remember about destructuring). But since the emergence of the ES6 ESTree spec, we have already broken the expectations you mention:

1. Function parameters are no longer just `Identifier` nodes, they can also be `AssignmentPattern` nodes (when default values are present).
1. `VariableDeclarator.id` can be `ObjectPattern` or `ArrayPattern` in addition to `Identifier`.

That's why I thought a new node type would fit in better than tacking on a type annotation to `Identifier`. Tools already are on guard that they might not be dealing with identifiers in these situations.

**Comment by jeffmo** [comment]
Also worth noting: Both TypeScript and Flow have custom toplevel statements that aren't just attachments to other nodes. I guess these are simpler to model, but I don't know that they can be modeled generically... (i.e. `declare class ...` or `import type ...`)

**Comment by RReverser** [comment]
> Also, I'm on Windows, so I can't run Flow myself.

I was using [outdated] Flow build for Windows for such purposes, I can drop a link when not on the phone.

> I looked at ASTExplorer - the examples you shared all seem to place  typeAnnotation  directly on  Identifier , which doesn't seem to be inline with the definitions in the file you share

Apparently I missed Identifier in definitions, but everything else should match (e.g. function return types, class props etc.). Sorry for desinformation :(

Anyway, ASTExplorer tree should be 100% compatible with Flow (@jeffmo correct me if I'm wrong), so I hope you'll enjoy the tool and it will be useful for discovery purposes.

**Comment by jeffmo** [comment]
> Function parameters are no longer just Identifier nodes, they can also be AssignmentPattern nodes (when default values are present).

That's a good point! Here's what Flow does for those: https://gist.github.com/jeffmo/e96ef1dfdef82bd71091

(looks like it just pops a `typeAnnotation` node on `ObjectPattern` as well)

> ASTExplorer tree should be 100% compatible with Flow

I haven't checked this lately, but if it's not it shouldn't be too far off (aka shouldn't be too difficult to get things aligned -- time permitting, etc).

**Comment by nzakas** [comment]
@jeffmo Yeah, it wasn't my intent to model those extra nodes, as I'm assuming there would be language-specific nodes as addons to ESTree. My goal was only to give type annotations a predictable place to live in ESTree so that tools like ESLint can make better decisions about what they're looking at.

**Comment by jeffmo** [comment]
@RReverser: So we have the ocaml flow parser compiling to JS now (https://www.npmjs.com/package/flow-parser).

I'll send a PR over to astexplorer here in a few to add it as a parser there.

**Comment by RReverser** [comment]
@jeffmo Awesome!! Let me know if you need any help.

**Comment by hzoo** [comment]
flow parser was added: https://astexplorer.net/#/ZMdgfX6CtJ

**Comment by jeffmo** [comment]
@nzakas: Curious about your thoughts on adding `typeAnnotation` properties as a general approach?

**Comment by ariya** [comment]
I have not using Flow extensively, but based on my exposure to the deprecated `esprima-fb`, generally speaking I don't mind the direction on its `typeAnnotation` extra property to indicate type annotation.

**Comment by nzakas** [comment]
@jeffmo if you're referring to `Identifier.typeAnnotation`, I'm not a big fan. I just don't think type annotations are logically children of `Identifier`. Having played with the TypeScript AST a bunch recently, I gained perspective on how properly defining these types of relationships makes tooling a lot easier, and it seems like having a node that's a parent of both the identifier and the annotation is clearer and will make tooling easier. 

For instance, with my original proposal, I can find all identifier type annotations by only visiting `TypedPattern` nodes. I think that is pretty powerful for tools like ESLint. Also, every ESLint rule that works with an `Identifer` and does any token or source inspection would have to check for the annotation and change its behavior, as opposed to assuming `Identifier` represents just an identifier.

If I'm the only one who feels this way, I'll defer to the consensus. I just really want to avoid creating further messes in ESTree (getter/setter, methods, shorthand properties) that make tooling harder. 

----

Elsewhere, it seems like the following matches what Flow is already doing and therefore aren't controversial?

```js
interface TypeAnnotation <: Node {}

extend interface FunctionDeclaration {
    returnType: TypeAnnotation | null;
}

extend interface FunctionExpression {
    returnType: TypeAnnotation | null;
}

extend interface ArrowFunctionExpression {
    returnType: TypeAnnotation | null;
}
```

Just want to narrow the scope of the discussion.

**Comment by jeffmo** [comment]
> Elsewhere, it seems like the following matches what Flow is already doing and therefore aren't controversial?

Yea, seems there's no controversy there.

> For instance, with my original proposal, I can find all identifier type annotations by only visiting TypedPattern nodes.

Not all TypedPattern nodes would be a type for an identifier though, right? They can also be types for a more complex pattern (i.e. a destructuring pattern) -- so two steps would still be required if you were truly only looking for an identifier with a type annotation given the wrapper design.

What I would've expected to be a little more common (of course, you have more context for eslint than I do here) would be cases where you were either (a) looking for all type annotations in general (in both designs you just search for a `TypeAnnotation` node) or (b) looking for a very specific one -- i.e. "annotations on variables named `x`" (In your design you find Identifiers and look up the tree ancestry to find a potentially-present sibling `TypeAnnotation` node, and in the Flow design you look down the tree at the nullable `typeAnnotation` property).

FWIW, using the current structure inside Flow hasn't proven to be any kind of burden -- but then again I don't know that using a composed form would have been much of one either. At worst, I think a wrapper node would only be a little more typing for cases like pattern matching or extracting info from a typed expression.

All that said, I actually don't really feel strongly here and I think either will get the job done. Just throwing in my 2cents from working with both in the past :)

**Comment by nzakas** [comment]
> Not all TypedPattern nodes would be a type for an identifier though, right?

Correct. It's possible that `left` could be any `Pattern`. However, if you were to care only about `Identifier` nodes, you can just query for those (for instance, in an ESLint rule), rather than navigating around. We end up doing a bit of this in several rules already due to `AssignmentPattern`.

> All that said, I actually don't really feel strongly here and I think either will get the job done. Just throwing in my 2cents from working with both in the past :)

I feel somewhat strongly, but also agree that both will get the job done. It's mostly just based on my experience with ESLint bugs thusfar. `Identifier.typeAnnotation` has already caused a couple of issues because we assume an `Identifier` always represents a single name. That means rules that deal with things like spacing get confused. With my proposal, I wouldn't need to do any work to properly support type annotations, and I'm always biased to not having to do work. :)

I guess the real deciding factor, outside of anyone else having a strong opinion, would be if Flow would be open to changing the structure based on this discussion? If not, then there's probably no point in continuing to discuss.

**Comment by jeffmo** [comment]
> I guess the real deciding factor, outside of anyone else having a strong opinion, would be if Flow would be open to changing the structure based on this discussion?

Flow probably won't change it's internal representation (it's too convenient and pervasive at this point), but the JSON output of the parser is just a conversion of the ocaml datastructures anyway. This conversion is mostly 1:1 today (the ocaml structures very closely mirror estree), but if things did diverge there is at least a place to manage that for anyone consuming the Flow parser via JSON.

(here's the converter for reference/posterity: https://github.com/facebook/flow/blob/master/src/parser/estree_translator.ml )

**Comment by nzakas** [comment]
Okay, so I guess we'd need to stick with that. :-/

Any other thoughts? @mikesherov

**Comment by DanielRosenwasser** [comment]
I don't think you want `typeAnnotation` on every `Identifier`. By not doing the work to structure the tree in a way that makes annotation locations specific, your consumers have to figure it out themselves. Even working on the tree internally, that's a really nice advantage. Just figured I'd weigh in.

**Comment by mikesherov** [comment]
@nzakas I'm not really up to speed on this issue. Seems like we just have to stick with it.

**Comment by nzakas** [comment]
Okay, I just want to make one final plea on this and then I'll let it go. :)

It seems incorrect to add `typeAnnotation` to `Identifier` since the type annotation is only relevant in specific situations and actually applies to the declaration and not the identifier itself. I'm still having a hard time rationalizing this based on how variable and argument declarations are represented currently. 

So I'm wondering if Flow didn't already do this, would we have arrived at this `typeAnnotation` property or would we have added another node?

As a side note: I'm really hoping ESTree doesn't devolve into "whoever does it first wins." I think we did a good job normalizing default parameters despite differences in initial implementations, and I'm hoping for continued discussions of that nature.

**Comment by jeffmo** [comment]
For me, having an AST that can never represent an invalid program is more of a nice-to-have than considerations for compatibility and some form of standardization (ESTree already fails the "invalid-program representation" test in a few places). Additionally ESTree doesn't currently distinguish lvalues from rvalues -- so when we made our design, adding a `typeAnnotation` property was the least intrusive and most practical solution considering both generic and non-generic traversers.

I don't think we have to choose the direction Flow chose simply because Flow chose it. There is already a place to in Flow to shim it's internal ocaml representation before it is exposed as JSON, so choosing the alternate design here is tractable from Flow's perspective. I don't know that there really is a ton of tooling built on top of Flow's AST output, so changing that representation probably won't pose a huge problem.

There's always an interesting chasm between "what would we do if we were starting from scratch" and "what do we do given that we're not" for designs like this. In this case, I don't see truly fundamental flaws in Flow's approach so, even if I weren't actively working on Flow, I would probably be inclined to just go with what's already there. The caveats are real, but it's really nothing intractable (we know this because we're living with it).

Anyway, I really truly am ok with either of the 2 options on the table -- so I'll leave the rest of the discussion to others from here on out :)

**Comment by nzakas** [comment]
> There's always an interesting chasm between "what would we do if we were starting from scratch" and "what do we do given that we're not" for designs like this. In this case, I don't see truly fundamental flaws in Flow's approach so, even if I weren't actively working on Flow, I would probably be inclined to just go with what's already there. The caveats are real, but it's really nothing intractable (we know this because we're living with it).

Indeed. My main concern is that we've seen pain from latching on to existing nodes in the past. The `Property` node is the biggest example of this, where it was made to represent each type of thing in an object, and modifying `Identifier` in this way feels vaguely similar to me. Granted, I've been a bit spoiled working with TypeScript's AST lately, where everything seems to be really clear, and my hope for ESTree is that going forward we can make more unambiguous parts of the tree.

**Comment by mikesherov** [comment]
@nzakas, I agree. But unless everyone is willing to spec out the "experimental" stuff together, we're doomed to document the existing stuff.

**Comment by nzakas** [comment]
@mikesherov agree, and that's what I'm trying to do here. :)

**Comment by nzakas** [comment]
Okay, seems like no one else wants to wade on this, so there's basically two ways we can go to close this up:

1. Document what Flow has, call those the "official" type extensions for ESTree.
1. Don't document anything and say, "hey, y'all do whatever" and not worry about it.

I can see arguments for each, does anyone have a strong opinion?

**Comment by mikesherov** [comment]
I'm fine with documenting flow personally. 

Mike Sherov

**Comment by DanielRosenwasser** [comment]
Why are those the only two options? Where is the option for doing things the way @nzakas has described where annotations can correctly be placed at declaration sites? @jeffmo already said Flow's estree serialization could pretty easily reflect that.

**Comment by nzakas** [comment]
@DanielRosenwasser it doesn't seem like there's much support for my proposal.

**Comment by RReverser** [comment]
@nzakas I would be interested in exploring things that could be done better, but only if Flow, ast-types, recast and other tools that rely on it would participate and agree to change. Otherwise out design won't have any real impact and will be incompatible with existing use.

**Comment by nzakas** [comment]
@RReverser didn't realize recast and ast-types were already using the Flow way. In that case, there really is no choice. 

Would have been nice to have caught this for discussion earlier, before it was baked into everything. :-/

**Comment by RReverser** [comment]
@nzakas True. There is so much things that "could be done better if done properly from scratch"...
