### ISSUE TITLE
Represent the data in a flat format

### ISSUE THREAD

**Issue by prettydiff** [estree/estree#124]
This may not be the appropriate place to post this.  I only became aware of this project last night, and I can see that the parse scheme is already largely complete.

A solid way to represent all the project goals is to represent the parse data in a flat manner opposed to a tree.  A tree is a structure, which is awesome if structure is the desired output like for a compiler, but as I understand the project goals the parsed tokens are more desirable than the tree they come together to form.

In my own project I use a series of parallel arrays to represent the parsed tokens.  Here are the strengths of that approach:
- It is largely forward compatible by default.  You occasionally need to watch for new keywords that impact the code in unique ways different from other keywords, such as let and const.  The same applies for operators as well.  Most new operators and keywords, while each being unique in their own way, do not alter the structure or meaning of the code in fundamentally different ways from other already existing operators and keywords respectively.  Use just have to ensure they are captured appropriately by the lexer.
- It is largely always backwards compatible by default.  The parsed output is a reflection of the parser's rules which can be added or removed at will (provide solid unit tests for regression).  In my markup parser, for example, I am constantly adding new rules to support a wide variety of template languages directly as parsed tokens plus their unique comments and other unique qualities without disruption to standard syntax parsing.
- It is easily extensible.  Data types are just a data field.  You can add additional values to this field as you wish.  If new data fields need to be added then just ensure they are populated as the other arrays are populated so as to ensure all data fields (parallel arrays) remain parallel in their values.
- The data is flat, which means its values are dramatically faster to traverse than a large multi-dimensional object.  Such data is generally a little bit slower to generate than an AST (in some cases twice as slow), but the data is already well reasoned and dramatically faster to access for all consuming applications.
- Structures can still be represented in flat data.  I found in my JavaScript parser that I needed to know in what kind of container any given token resides and what is coming or what precedes.  So, I defined structure definitions and included these as an extra data field as well as the token index where the local structure begins.  This allows me to reason upon the data no differently than if it were provided as a structure, somewhat like walking the DOM.

For an example of the concept you can play around with the parse scheme in Pretty Diff v2.0.0 alpha release which can be accessed from the v2.0.0 branch on github or at http://prettydiff.com/ignore/testlocation/?m=parse.  For just a quick demo I recommend running the tool in the browser and checking the options `Formatted as an HTML table` and `Render HTML`.

**Comment by mikesherov** [comment]
While there are great use cases for using token arrays instead of trees (and indeed, Acorn, Babylon, and Esprima all can produce one), there is immense value in producing an AST for interpreters and linters, and this spec is just an attempt to document and standardize the tree portion at this moment.
