### ISSUE TITLE
include CaseBlock inside SwitchStatement for better lexical scoping

### ISSUE THREAD

**Issue by jayphelps** [estree/estree#125]
Parsers that use ESTree AST spec do not output a [`CaseBlock` node](http://www.ecma-international.org/ecma-262/6.0/#sec-switch-statement) which 1. makes it super easy to forget that `SwitchStatements` have a block that should create a new lexical env and 2. if they do realize it, makes it harder for them to apply the same common code paths they use for other `BlockStatement` et al. because the next level down is just an array of  `SwitchCase` nodes, for each individual branch. Instead they probably will fudge their `SwitchStatements` visitors to be block-like or patch the AST before traversing.

As an example, I recently discovered Babel doesn't handle switch statement block scoping correctly and seemingly because of these reasons. Here's the [babel PR to fix that](https://github.com/babel/babel/pull/3490), which takes the hacky approach of pretending `SwitchStatement` is block-like but I feel is much more brittle than if the AST used `CaseBlock`.

```js
let foo = 1;
switch (true) {
  case true:
    let foo = true;
  case true:
    foo = false;
    // CaseClauses share scope of CaseBlock
    // so we're reassigning foo from true to false
    // not from 1 to false
    break;
}

foo;
// should be 1 because of `CaseBlock` creating new lexical env

```

**Comment by mikesherov** [comment]
Thanks for contributing! This would be a backwards incompatible change to the spec, and therefore not possible to do.

Even if we could introduce backwards incompatible changes, I would personally be 👎 on this, as it's a completely superfluous node in the tree.

**Comment by jayphelps** [comment]
The existence of the node itself has meaning, so it is not superfluous. While I respect your choice, I do think it's odd that you'd prioritize succinctness over correctness. Thanks for your time. ✌️

**Comment by mikesherov** [comment]
@jayphelps thanks again for contributing. It's not an issue of correctness, unless you mean correctness to be a 1-to-1 exact mapping of grammar from the spec, which has never been nor will be the goal of ESTree. There are many other "missing" nodes if you're looking for conformance to the spec.

When I say it's superfluous, I mean that all SwitchStatements have exactly one CaseBlock, so the existence of that node in the tree does not disambiguate or modify the meaning of the tree. 

Lastly, considering that Babel now uses it's own AST format (Babylon), if you feel passionately about this, I'd suggest you propose this modification to that format instead. I suspect you'll get the same feedback, but hey, you never know!
