### ISSUE TITLE
Minor Esprima-spec inconsistencies: ConditionalExpression and TryStatement

### ISSUE THREAD

**Issue by austinbyers** [estree/estree#126]
I've implemented a Python module for [AST Traversal](https://github.com/austinbyers/esprima-ast-visitor) based on this spec, but I noticed two inconsistencies between the specification and the actual AST format printed by [Esprima](http://esprima.org/). I realize that this project has nothing to do with Esprima specifically, but their changes do make sense:

1. In [ConditionalExpression](https://github.com/estree/estree/blob/master/spec.md#conditionalexpression), the spec lists the fields as [`type`, `test`, `alternate`, `consequent`], but Esprima outputs [`type`, `test`, `consequent`, `alternate`]. The latter order makes more sense, I would think.
2. In [TryStatement](https://github.com/estree/estree/blob/master/spec.md#trystatement), Esprima adds `guardedHandlers` and `handlers` (both lists) before the `handler` field. In this case, I don't know if Esprima broke from the spec or if the spec is slightly out of date. As it stands, I'm not sure how the spec would handle catching multiple different exceptions.

**Comment by RReverser** [comment]
@austinbyers As for the (1), order is completely unimportant - it's just a set of named fields in the object. As for (2) it was a legacy Mozilla / Esprima thing that they likely preserved for the backward compatibility. There is not such thing as catching different exceptions in JavaScript.

**Comment by ariya** [comment]
For the second point, see also https://github.com/jquery/esprima/issues/1030.
