### ISSUE TITLE
meaning of "<:"

### ISSUE THREAD

**Issue by ciez** [estree/estree#128]
may I ask what "<:" stands for?

for example, how to interpret this interface:

interface FunctionExpression <: Function, Expression {
    type: "FunctionExpression";
}

?

**Comment by RReverser** [comment]
It just denotes "implements" / "extends" in the spec interfaces.

**Comment by ciez** [comment]
does this mean that FunctionExpression 
a) may contain some or 
b) must contain all properties 

from Function / Expression ?

**Comment by RReverser** [comment]
Well, `Expression` is just a "tag interface", it doesn't contain any properties. As for `Function`, yes, it should contain all properties with same types.

**Comment by ciez** [comment]
Thank you very much. Appreciate this.
