### ISSUE TITLE
Is there a name for the syntax used to describe the AST nodes?

### ISSUE THREAD

**Issue by marcospassos** [estree/estree#133]
Hi folks!

Is there a name for the syntax/language adopted to describe the AST nodes?

**Comment by RReverser** [comment]
No, it's just a custom DSL.

**Comment by marcospassos** [comment]
Thank you.

**Comment by olsonpm** [comment]
stumbled on this now - would you guys be open to making a comment in the README?  The syntax just looks like it was taken from somewhere and I was hoping to find documentation on it.

**Comment by mikesherov** [comment]
@olsonpm please do!
