### ISSUE TITLE
Standardize CommonJS "Program" node flag?

### ISSUE THREAD

**Issue by loganfsmyth** [estree/estree#136]
In Babili, we've been talking recently about the potentially subtle distinctions between minifying individual CommonJS modules, and minifying spec-compliant "script" files, and the possibility of standardizing on a third `sourceType` for CommonJS modules came to mind, e.g. `sourceType: commonjs`. 

CommonJS is already special-cased in ESLint's espree via `globalReturn` and Babylon/Acorn via `allowReturnOutsideFunction`, but that flag doesn't get represented in the AST anywhere unless a return statement exists, meaning that given a `sourceType: script` AST, you have no way of knowing. This means anything that expects to take an AST to process for scope analysis cannot know if a top-level `var` should be considered a global variable or a module-scoped variable. This also feels like something that could benefit ESLint too, but I don't have solid examples for that.

The downside being that obviously CommonJS is not an endorsed parser target for the ECMAScript spec.

If the answer is just No for this, no worries, but I was curious to see if there was interest because it does seem like it could benefit the overall JS tooling ecosystem to have a way to flag this distinction.

**Comment by nzakas** [comment]
I'd prefer to stick to spec-specified compilation targets. ESLint already works correctly for CommonJS, so I don't see a big benefit there.

**Comment by loganfsmyth** [comment]
The cases I had in mind for ESLint for example would be

```
/*eslint-env browser */
/*eslint no-global-assign: 2 */

var HTMLElement = {};
```

the rule fails without the `var`, but the same global assignment is happening even with the `var` present, if the file is a global script instead of CommonJS.

**Comment by nzakas** [comment]
I still don't see that as a big enough deal to introduce something nonstandard into ESTree.

**Comment by loganfsmyth** [comment]
That's fair, and I kind of assumed that would be the answer. Babili will have to make up its own flag then.
