### ISSUE TITLE
Why does ForInStatement allow both VariableDeclaration or Pattern as left property?

### ISSUE THREAD

**Issue by krisnye** [estree/estree#139]
I assume it is for backwards compatibility purposes with Mozilla AST, but it seems redundant since a VariableDeclarator already supports id:Pattern.

    interface ForInStatement <: Statement {
        left: VariableDeclaration |  Pattern;
    }

    interface VariableDeclarator <: Node {
        id: Pattern;
    }

**Comment by loganfsmyth** [comment]
These are both valid

```
// With a variable declaration
for (var {foo} in bar) {}
```
and
```
var foo;

// Just a pattern.
for ({foo} in bar) {}
```

**Comment by krisnye** [comment]
So in the first case it will be a VariableDeclaration and in the second it will be a Pattern.

If you just do:

    var foo;
    for (foo in bar) {}

Then will left be just an Identifier?

**Comment by loganfsmyth** [comment]
Yes, because `Identifier` is a pattern: https://github.com/estree/estree/blob/master/es5.md#identifier
