### ISSUE TITLE
CallExpression and NewExpression

### ISSUE THREAD

**Issue by ghost23** [estree/estree#140]
Hello,

for the es5.md specification I would like to propose to have CallExpression and NewExpression to extend a new interface, like `CallableExpression` or something (I am not good with names), which would look like this:

```
interface CallableExpression <: Expression {
    callee: Expression;
    arguments: [ Expression ];
}
```

And CallExpression would then look like this:

```
interface CallExpression <: CallableExpression {
    type: "CallExpression";
}
```

And consequently NewExpression like this:

```
interface NewExpression <: CallableExpression {
    type: "NewExpression";
}
```

This is a more correct way of describing the type property in these circumstances and you have already done this in a somewhat similar case with `Function` and `FunctionDeclaration` and `FunctionExpression` where you deliberately left out `type` from the `Function` interface and only specified it in the other two.

The reason, why I would like to see that change is, that it makes it easier to create typescript classes based on the specification, because in a typescript interface overriding a string literal in an extended interface is forbidden.

**Comment by loganfsmyth** [comment]
Not really in a place to comment on this addition, but I will say `CallableExpression` seems like an iffy name since in most uses `callable` is something that _can_ be called, not something that _is_ being called.

**Comment by ghost23** [comment]
Yes, sure, I'm open for any name, that might better suited.

**Comment by RReverser** [comment]
> The reason, why I would like to see that change is, that it makes it easier to create typescript classes based on the specification, because in a typescript interface overriding a string literal in an extended interface is forbidden.

Various things work differently in DefinitelyTyped definitions of ESTree to make them more precise than this DSL can describe, we anyway can't express all of them, and this is not really a goal.

But on a general note, I'm fine with such changes as they're not breaking.

**Comment by ghost23** [comment]
Can you give an example of what's working differently? The only thing I found so far (despite the quirks with overriden string literals and an issue with ArrowFunction body overriding) is the addition of questionmarks here and there in definitlytyped. Something by the way, I think should also be added to the specs here, because it would be a useful information in the spec to know, which properties are optional.

**Comment by RReverser** [comment]
@ghost23 Here we have no optional properties, as this spec is intended to be language-agnostic and omitting them in TypeScript is just a convenience, not spec behavior. Instead, you can pass `null` to some properties.

**Comment by RReverser** [comment]
> Can you give an example of what's working differently?

@ghost23 Did you look at modern definitions or legacy ones?

Here are the ones that are actually installed with `@types/estree`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/estree/index.d.ts

So yes, other things are overriding `type`, arrow functions, also parent -> child relationship - for example, spec DSL uses parents for tag interfaces, which TypeScript doesn't support and instead requires listing all of the descendants for type safety like in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/estree/index.d.ts#L34. That is something I'm pretty sure we don't want to change just to align with TypeScript quirks.

**Comment by ghost23** [comment]
Ah, ok. So a tool like esprima would always create all these properties and put null to some? Did not know that.

Anyway, since you're principally OK with the change, I would now prepare a pull request. You can then decide, if you want to take it in. I have another similar case with ForInStatement and ForOfStatement which I would include there, too.

**Comment by RReverser** [comment]
> for example, spec DSL uses parents for tag interfaces, which TypeScript doesn't support and instead requires listing all of the descendants for type safety like in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/estree/index.d.ts#L34. That is something I'm pretty sure we don't want to change just to align with TypeScript quirks.

That last example is also somewhat relevant to your proposal, as shows yet another way how TypeScript inheritance won't align with spec anyway, even with the proposed change.

**Comment by ghost23** [comment]
Ah, ok, I guess I was looking at old ones. I don't really understand, what you mean by "parents for tag interfaces". You can extend from multiple parent interfaces, right? Something like:

```
interface Identifier extends Expression, Pattern {
	type: "Identifier";
	name: string;
}
```

**Comment by ghost23** [comment]
Here is a test parsing I did, provided, that the specification would have the changes I am proposing. The only problem I see that is left, is the `body` property of the `ArrowFunctionExpression`.

**Comment by RReverser** [comment]
@ghost23 I mean the way we use references to e.g. `Expression` which is in fact just a tag that limits accepted types and not interface defining any fields.

**Comment by ghost23** [comment]
I am dropping the proposal. I will instead generate those additional parent interfaces programmatically during my parsing phase.

**Comment by RReverser** [comment]
@ghost23 FWIW, judging from description of your repo, you're recreating https://github.com/estree/formal :)

**Comment by ghost23** [comment]
I know :)

It is partly a fun exercise of building a little parser and partly, that I saw some things in estree/formal I thought I could improve, like for instance providing literal types, like:

```
type UpdateOperator = "++" | "--";
```
instead of just
```
type UpdateOperator = string;

**Comment by RReverser** [comment]
@ghost23 Ah yeah, that's from the time TS didn't support string types in stable version, def can be improved. Although given the differences, I'm rather convinced that manually maintained TS definitions are more reliable :)
