### ISSUE TITLE
Do the interfaces require the properties to be own?

### ISSUE THREAD

**Issue by isiahmeadows** [estree/estree#142]
I was wondering if they needed to be *own*, instead of getters/setters either own or on the prototype, backed by private data for memory reasons (far smaller objects). If I could, I would be able to pack the size of, say, `UnaryExpression` down to 1 integer (type, operator, and prefix can be packed) + 2 object references (source location + argument).

Or, in other words, are instances of this class considered `UnaryExpression`s?

*(`get type` and `get operator` return strings, by the way.)*

```js
class UnaryExpression {
    constructor(mask, loc, argument) {
        this._m = mask | Types.UnaryExpression
        this.loc = loc
        this.argument = argument
    }

    get type() { return Types[this._m & Mask.Types] }
    set type(type) { this._m = (this._m & ~Mask.Types) | Types[type] }
    get operator() { return Operators[(this._m & Mask.Operators) >> Mask.OpEnd] }
    set operator(op) { this._m = (this._m & ~Mask.Operators) | (Operators[op] << Mask.OpEnd) }
    get prefix() { return (this._m & Mask.Prefix) !== 0 }
    set prefix(prefix) { this._m = (this._m & ~Mask.Prefix) | (-prefix & Mask.Prefix) }
}

const Mask = mkEnum({ /* ... */ })
const Types = mkEnum({ /* ... */ })
const Operators = mkEnum({ /* ... */ })
```

**Comment by isiahmeadows** [comment]
Note that the above properties remain readable and writable both.

**Comment by mikesherov** [comment]
ESTree, as a spec, really only abstractly defines the tree. It can be expressed as YAML, JSON, XML, JS objects, Python, etc.

As far as the JS ecosystem goes, as long as the updateExpression is an object with the properties defined by the spec, it's a valid ESTree. Constructors, setters, and other additive properties are orthogonal.

That's at least my opinion.

**Comment by isiahmeadows** [comment]
@mikesherov I know that some JS tools in practice will modify the objects in-place instead of replacing them, which is why I asked.

**Comment by RReverser** [comment]
@isiahmeadows With getter and setter modifying objects should just work as before, no? Same for `Object.keys`.

**Comment by mikesherov** [comment]
Right, but EStree is only about data structure, not mutability, etc. It's a great question... just clarifying that ESTree has no opinion.

**Comment by isiahmeadows** [comment]
@RReverser I was mostly asking about specifics on how the data must be laid out in memory, with my possible `UnaryExpression` as an example.

**Comment by isiahmeadows** [comment]
@RReverser @mikesherov Thank you all, by the way! Question answered! :smile:
