### ISSUE TITLE
UnaryExpression "prefix" is always true

### ISSUE THREAD

**Issue by mroch** [estree/estree#147]
The `prefix` property of `UnaryExpression` seems like it will always be `true`. I'm guessing it's there based on [§12.5 UnaryExpression](http://www.ecma-international.org/ecma-262/6.0/#sec-unary-operators) which includes `PostfixExpression`, but estree puts those into `UpdateExpression` instead.

Proposal: delete the `prefix` property from `UnaryExpression`.

**Comment by RReverser** [comment]
Looks like duplicate of https://github.com/estree/estree/pull/118.

**Comment by mroch** [comment]
My bad, searched for issues but not PRs. Thanks!
