### ISSUE TITLE
May I join?

### ISSUE THREAD

**Issue by getify** [estree/estree#16]
I would like to be a member of this effort. I have on several occasions in the past tried to build support in the tooling community around similar efforts, most notably with this:

https://github.com/getify/concrete-syntax-tree

It didn't really get very far, but I continued working on such changes in my own fork of esprima since then. I would very much like to represent the needs of a tree format that can (optionally) preserve the concrete syntax elements (whitespace, comments, extraneous `(` and `) pairs, etc).

**Comment by impinball** [comment]
Have you heard of recast (https://www.npmjs.com/package/recast)? It pretty
much does that, up to and including source map support.

**Comment by mikesherov** [comment]
@impinball but it's not part of a standard. @getify is asking to join to push forward the concrete portion of the tree. @getify, send a PR adding yourself, and submit issues, that's how you join as of the moment.

**Comment by impinball** [comment]
@Mike I was more talking about the previous efforts. I'm currently working
on a converter between Acorn and Esprima WRT module differences. I do have
a few things that I probably should do to help with later extensibility,
though.

**Comment by impinball** [comment]
It's also a little too alpha to even put on GitHub (haven't gotten even
half of my tests passing ATM.

**Comment by Dashed** [comment]
> I would very much like to represent the needs of a tree format that can (optionally) preserve the concrete syntax elements (whitespace, comments, extraneous ( and `) pairs, etc).

OMG. Yes please!
