### ISSUE TITLE
AssignmentExpression.Left should have more restrictive type

### ISSUE THREAD

**Issue by cpcallen** [estree/estree#160]
In the ES5 spec, AssignmentExpression is defined as:

    interface AssignmentExpression <: Expression {
        type: "AssignmentExpression";
        operator: AssignmentOperator;
        left: Pattern | Expression;
        right: Expression;
    }

But in fact arbitrary expressions cannot appear on the left of an assignment statement.  I *think* the actual definition should be:

    left: Pattern | MemberExpression

(Where, at least in ES5, Pattern is just Identifier.)

The same issue applies to UpdateExpression.Argument.

**Comment by michaelficarra** [comment]
Sorry, but you're mistaken. `f() = a;` and `new F = a;` are uncommon but valid ES5 programs.

**Comment by NeilFraser** [comment]
@michaelficarra Fascinating.  Can you provide an example?  I can't think of what `f()` could return that would be assignable.

**Comment by michaelficarra** [comment]
@neilfraser Check out the Reference type in ECMA262. Functions can return References. But these productions are no longer allowed in assignment position as of ES2015.

@cpcallen I'd have to look at ES5 again to remind myself, but I'm betting that programs like `1 = 0;` were also valid in ES5, though would unconditionally throw.

**Comment by getify** [comment]
`1 = 0` is in fact legal syntax. It's disallowed as a `ReferenceError`, but that's at runtime.

**Comment by RReverser** [comment]
Relevant: #135 that attempts to fix it.

**Comment by RReverser** [comment]
@getify It's not valid syntax (restricted by early error) since ES5.

**Comment by getify** [comment]
@RReverser gives referenceerror in chrome.

**Comment by RReverser** [comment]
@getify Yeah but it's just how such early error is observed from JS. Even if you declare function with such assignment but don't execute it, error is still thrown while parsing.

**Comment by cpcallen** [comment]
@michaelficarra: My reading of ECMA262 5.1 agrees with yours.

I do think it's a bit bizarre that it's spec'ed that way, and I'm guessing that there are few if any ESTree-compatible parsers that will produce productions other than Identifier and MemberExpression (Neither Esprima nor Acorn will), but the spec as it stands is certainly pedantically correct.

**Comment by michaelficarra** [comment]
The best kind of correct! :smile:
