### ISSUE TITLE
AssignmentExpression: shouldn't the left-hand side be either an identifier or a pattern?

### ISSUE THREAD

**Issue by fflorent** [estree/estree#165]
The [assignment expression paragraph](https://github.com/estree/estree/blob/master/es5.md#assignmentexpression) precises the left-hand side as being an expression.

But AFAICT none of the expressions can be the left-hand side part of an assignment…

I wonder why it's not just an identifier instead of an expression ?

Cheers,
Florent

**Comment by michaelficarra** [comment]
Sorry, but those can be the LHS of an assignment. Just because they unconditionally cause runtime errors does not mean they aren't programs. `f() = 0;` was a program pre-ES2015, and `if(false) { f() = 0; }` would evaluate just fine.

**Comment by fflorent** [comment]
Oh Jeez, JS…

Thanks for the information!

Florent
