### ISSUE TITLE
BigInt

### ISSUE THREAD

**Issue by jamiebuilds** [estree/estree#169]
Babylon [represents](https://github.com/babel/babylon/pull/588) BigInt as:

```js
{
  type: "BigIntLiteral",
  extra: {
    rawValue: "0b101011101",
    raw: "0b101011101n"
  },
  value: "0b101011101"
}
```

But it's not obvious how estree will represent them.

- Right now `Literal` is overloaded to mean different things depending on the type of `node.value`
- Since strings are already taken by strings, there will need to be something to distinguish strings and big ints

Options:
1. New property on `Literal` more accurately describing which type it is. i.e
```js
{ 
  type: "Literal",
  kind: "string" | "number" | ... | "bigint"
  value: string | number | boolean | ...
}
```
2. Extend the `Literal` type with a new `BigIntLiteral` type

I figure people will be most in favor of 2 since there's already a RegExpLiteral node.

**Comment by michaelficarra** [comment]
I'm for option 2 to be consistent with RegExp literals.

```js
{ type: "Literal", value: 0n, bigint: "0n" }
```

**Comment by mikesherov** [comment]
I am also for number 2, even if it would be "consistent" with the majority of ESTree literals (let's not repeat mistakes of the past). It would be a bit surprising for consumers of ESTree, but this is a cleaner future.

@RReverser @ariya any thoughts?

**Comment by ariya** [comment]
👍  for `bigint` property in the `Literal` node.

**Comment by adrianheine** [comment]
In #179 the question of how to handle the `value` property on host engines that don't support bigint arised.
