### ISSUE TITLE
What would an Incremental Parsing api look like?

### ISSUE THREAD

**Issue by rektide** [estree/estree#17]
[Esprima just closed a 3 year old ticket on Incremental parsing](https://code.google.com/p/esprima/issues/detail?id=92#c11):

> Once we have a better idea how to implement this, we'll restart the topic

Meanwhile in [Shift Parser](https://github.com/shapesecurity/shift-parser-js/issues/6#issuecomment-69398002),

> What about the interface? Do you want to change all the lIst in the AST to generators?

What do people think such an API might look like? What would be an ideal outcome for an incremental  AST?

**Comment by impinball** [comment]
Here's a few ideas straight from my head.

```js
.parseIncrementally(source: string, opts: object)
.parseIncrementally(source: ArrayBuffer, opts: object)

.parse(source: string, opts: object with incremental: true)
.parse(source: ArrayBuffer, opts: object with incremental: true)
```

You could also accept a Node.js buffer by simply doing this early in the method:

```js
if (data instanceof Buffer) {
  data = data.toArrayBuffer();
}
```

I don't really understand what the best way would be, although I do know IDEs and build systems consuming large amounts of JS would greatly benefit (the code bases that UglifyJS2, etc. seriously choke on).

**Comment by RReverser** [comment]
I guess this does not relate to AST spec but rather to specific parser's implementation, and each parser might provide own techniques and APIs in order to achieve this goal in the best way for it's needs.

**Comment by impinball** [comment]
Yes, more or less.

**Comment by mikesherov** [comment]
@rektide, I'm going to close this to make sure we remain focused on the task at hand: defining an AST structure.

Reply on the ticket if you feel it should remain open instead.

**Comment by rektide** [comment]
It's a little hurtful that we're defining this spec without regard to incremental parsing. While I don't want to take away the usefulness of the fully parsed case, there's no way an incremental parser is ever going to be able to implement most of this AST, because it's littered with arrays and not some other more generative concept.

```
interface Program <: Node {
    type: "Program";
    body: [ Statement ];
}
```
https://github.com/estree/estree/blob/master/spec.md#programs

**Comment by impinball** [comment]
So, in other words, it's impossible to implement these as generators, and
gradually populate a return array? I find that hard to believe.
