### ISSUE TITLE
Stepping Down as Maintainer

### ISSUE THREAD

**Issue by mikesherov** [estree/estree#178]
Hey everyone,

I'm not really directly involved in projects that are using ESTree as the defacto standard anymore. I've stepped down from maintenance on Esprima a little while back, and as such, haven't been paying close attention to this space for a while.

I'm happy to leave responsibility in the hands of where it already mostly is: @michaelficarra, @RReverser, @hzoo, @nzakas, @ariya, or whoever else is still doing great work in this area.

Please let me know if you have any questions, but for now, I'm simply unsubbing from this repo and removing my ownership role.

**Comment by RReverser** [comment]
Bye @mikesherov and thanks for all your work on the standard!
