### ISSUE TITLE
Tracking early proposals

### ISSUE THREAD

**Issue by sebmck** [estree/estree#18]
Some early proposals will need to be parsed before they have been completely finalised for use in linters and most notably transpilers. To ensure interoperability an AST needs to be agreed upon prior to their finalisation.

How should these early proposals be regulated?

**Comment by mikesherov** [comment]
Seems to me that whenever a new structure is being parsed, before any of the projects here implement it, we issue PR here describing structure with justifications.

Once landed, everyone can proceed forward. In the estree spec, we must mark these structures as experimental and subject to change. However, any change at that point should be motivated by a change in ES spec only.

Seems like the only sane way forward, no?

@sebmck, care to open a PR noting this process in the README?
