### ISSUE TITLE
How to represent a computed Property?

### ISSUE THREAD

**Issue by FireCubez** [estree/estree#195]
i.e. `({a: 1, [b]: 2, c: 3})`

**Comment by FireCubez** [comment]
I've seen it done as a `computed` property on the Property node but I don't see that standardized here.

**Comment by not-an-aardvark** [comment]
It looks like it's specified [here](https://github.com/estree/estree/blob/df2290b23a652e1ec354b6775459a3b42e22f108/es2015.md#expressions):

> ```js
> extend interface Property {
>    key: Expression;
>    method: boolean;
>    shorthand: boolean;
>    computed: boolean;
>}

**Comment by RReverser** [comment]
Yep.
