### ISSUE TITLE
Revisit Dynamic Imports

### ISSUE THREAD

**Issue by mysticatea** [estree/estree#197]
Hello.

Currently, AST for dynamic imports is using `CallExpression`: https://github.com/estree/estree/blob/2c161ae714c1b23198be3be08c930e55a621c187/experimental/import-expression.md
But I think an independent node type is better:

```ts
interface ImportExpression <: Expression {
    type: "ImportExpression";
    source: Expression;
}
```

For some reasons:

- `source` property is consistent with [ImportDeclaration](https://github.com/estree/estree/blob/2c161ae714c1b23198be3be08c930e55a621c187/es2015.md#importdeclaration) to express importing source.
  On the other hand, it's hard to read that `arguments[0]` express the importing source.
- Searching `CallExpression`s which have `Import` node in that `callee` is not convenient to analyze dependencies.
- The `arguments` property doesn't fit Dynamic Imports syntax.
    - The syntax cannot have multiple arguments. (i.e. `import()` and `import(a, b)` are syntax error)
    - The syntax cannot have trailing commas. (i.e. `import(source,)` is syntax error)
- [EDIT] `Import` node is not consistent with `import.meta` meta property. Existing `MetaProperty` node represents `import.meta` without `Import` node. The `Import` node will confuse us in the future.

Thoughts?

Thank you.

----

- Previous discussion: https://github.com/estree/estree/pull/137

**Comment by j-f1** [comment]
How would `import.meta.url` be represented then?

**Comment by mysticatea** [comment]
It's the same way as `new.target` -- Using [MetaProperty](https://github.com/estree/estree/blob/master/es2015.md#metaproperty) node. Both `meta` and `property` properties are `Identifier` nodes.

```jsonc
// new.target
{
    "type": "MetaProperty",
    "meta": { "type": "Identifier", "name": "new" },
    "property": { "type": "Identifier", "name": "target" }
}

// import.meta
{
    "type": "MetaProperty",
    "meta": { "type": "Identifier", "name": "import" },
    "property": { "type": "Identifier", "name": "meta" }
}
```
