### ISSUE TITLE
ArrowExpression vs ArrowFunctionExpression

### ISSUE THREAD

**Issue by sebmck** [estree/estree#2]
Currently both esprima and acorn use `ArrowFunctionExpression`.

- jquery/esprima#1013
- https://code.google.com/p/esprima/issues/detail?id=567
- https://bugzilla.mozilla.org/show_bug.cgi?id=913617

**Comment by jeffmo** [comment]
Esprima intends to switch to ArrowExpression in its next major release

**Comment by ariya** [comment]
...unless, per Mozilla [bug 913617](https://bugzilla.mozilla.org/show_bug.cgi?id=913617) above, Mozilla really executes the plan to switch from ArrowExpression to ArrowFunctionExpression.

An alternative would be to use `ArrowFunction`, the term used in the ES 6 grammar.

**Comment by sebmck** [comment]
How about just keeping `ArrowFunctionExpression`?

**Comment by ariya** [comment]
I am for staying with `ArrowFunctionExpression`, I still think that's the most descriptive name. But that depends if SpiderMonkey is going to change `Reflect.parse` or not. IIRC this didn't happen (yet) because there are other Mozilla tooling relying on `ArrowFunction`.

**Comment by mikesherov** [comment]
@dherman, care to fill us in on plans here?

**Comment by dherman** [comment]
I'll have to ask around. I'm not sure how much tooling would have to change but I wouldn't imagine it's too bad. I'll report back.

**Comment by ariya** [comment]
@dherman Any data points on the tooling change effort?

**Comment by dherman** [comment]
Looks like it shouldn't be a problem for Mozilla at all. I built https://github.com/dherman/samo and grepped the addons ecosystem and found zero uses of Reflect.parse. I searched mxr for uses in the FF front-end and there are very few. So it should be pretty easy for us to make incompatible changes.

**Comment by sebmck** [comment]
Closed via 321c836a849f3d7f2797935e7c7b5b494bd9648c.

**Comment by dherman** [comment]
For reference I've submitted a SpiderMonkey patch for feedback: https://bugzilla.mozilla.org/show_bug.cgi?id=913617#c2

**Comment by dherman** [comment]
My fix to SpiderMonkey landed so hopefully by tomorrow Firefox Nightlies will have `ArrowFunctionExpression`.

**Comment by RReverser** [comment]
Cool! I guess we can merge #45 now?
