### ISSUE TITLE
Export * as ns from "source" representation

### ISSUE THREAD

**Issue by mck89** [estree/estree#202]
The [proposal](https://spectranaut.github.io/proposal-export-ns-from) to enable the new syntax `export * as ns from "source"` has been merged into EcmaScript standard on master for the 2020 edition.
I don't see any change about it in es202.md, how can i represent it?

**Comment by RReverser** [comment]
You'd probably want to extend [`ExportAllDeclaration`](https://github.com/estree/estree/blob/master/es2015.md#exportalldeclaration) with `id` property, unless others have better ideas.

**Comment by RReverser** [comment]
Actually, no, it's a specifier, so you'd need to add a new interface similar to `ImportNamespaceSpecifier` but for exports.

**Comment by mck89** [comment]
All specifiers extend `ModuleSpecifier` that have the `local` property, does that make sense in this case? What would it be? Why don't just extend `ExportAllDeclaration` as you proposed before? Maybe with a property called `exported` like the one in `ExportSpecifier` with the same meaning

**Comment by RReverser** [comment]
@mck89 It depends on whether something like `export * as ns, { other } from './source.js';` would be ever allowed. If it might be, then `* as ns` should be just one of the specifiers in a list, if not, then yeah, `ExportAllDeclaration` should work.

**Comment by loganfsmyth** [comment]
Is overloading `ExportAllDeclaration` desirable from a semantic perspective? You're not exporting `All`, we're exporting a specific single object that happens to be a namespace. Even if we don't think we need to worry about `export * as ns, { other } from`, it still seems like a strange override. Perhaps it would be nicer as `ExportNamespaceDeclaration`? I think that or `ExportNamespaceSpecifier` with `ExportNamespaceDeclaration`. I agree that `local` doesn't seem right in that context, but perhaps we can rework the definitions to just not `local` there?

**Comment by mck89** [comment]
Well you are still exporting `All` but using a namespace so i don't think that overloading `ExportAllDeclaration` is semantically wrong. Anyway i agree that it's not suitable for future syntax changes, i proposed this solution because adding a `Specifier` would inherit the `local` property and i can't think of a way to bypass this since all the specifiers intherit from `ModuleSpecifier` that has that property.

**Comment by mck89** [comment]
I want to share some other solutions i thought about:

**Solution 1**
Create a new interface `ExportNamespaceSpecifier` that extends `ExportSpecifier` and make the `local` property on `ModuleSpecifier` accept null values (for this new interface it will always be null).

**Solution 2**
Create a new interface `ExportNamespaceSpecifier` that does not extend `ExportSpecifier` (so without the `local` property), then make the `specifiers` property of `ExportNamedDeclaration` accept this interface, like:
`specifiers: [ ExportSpecifier | ExportNamespaceSpecifier ]`

Compared to the first solution i proposed these can be less clear since `export * from "source"` and `export * as ns from "source"` are represented in completely different ways, but the advantage is that they are fully future compatible.

If you prefer one of these solutions i'll try to submit another pull request.

**Comment by adrianheine** [comment]
The original proposal also had an [estree proposal](https://github.com/leebyron/ecmascript-more-export-from/blob/master/ESTree.md), did you take that into account?
