### ISSUE TITLE
Nullish coalescing operator `??`

### ISSUE THREAD

**Issue by jorendorff** [estree/estree#203]
Stage 3 proposal
Spec repo: https://github.com/tc39/proposal-nullish-coalescing

(Related to #146 optional chaining, but an independent proposal.) We just implemented `??` in SpiderMonkey. It's a short-circuiting binary operator, more like `||` than anything else, but calling it a `LogicalExpression` is a stretch.

**Comment by RReverser** [comment]
Hmm. Adding it as a `LogicalExpression` operator could be nice / easy implementation-wise, but I see why semantically it doesn't make much sense.

@hzoo @loganfsmyth @danez What do you think?

**Comment by michaelficarra** [comment]
`LogicalExpression` seems fine to me.

**Comment by codehag** [comment]
In the specification `LogicalExpression` is updated to `ShortCircuitExpression` - does it make sense to update it here as well?

**Comment by michaelficarra** [comment]
@codehag The organisation and names of the grammar productions in the spec should not affect our designs here. Also, estree cannot make backward incompatible changes such as the one you suggest.

**Comment by codehag** [comment]
ok, thanks for the context

**Comment by jorendorff** [comment]
Thanks for the replies here. We're implementing this in SpiderMonkey with `"LogicalExpression"` in <https://phabricator.services.mozilla.com/D52690>.

**Comment by fabiosantoscode** [comment]
:+1: Terser will follow suit.

**Comment by JLHwung** [comment]
This issue is fixed by #211.

**Comment by RReverser** [comment]
@JLHwung Right, thanks.
