### ISSUE TITLE
Eliminate empty .guardedHandlers

### ISSUE THREAD

**Issue by dherman** [estree/estree#24]
I filed a premature drive-by fix to this in [this failed PR](https://github.com/estree/estree/pull/15) but we need consensus first. I propose we eliminate the empty .guardedHandlers from the spec since it serves no purpose -- the deprecated spec includes the full definition and meanwhile tools can harmlessly produce an empty .guardedHandlers array and be spec-compliant so it seems likes a harmless fix.

**Comment by RReverser** [comment]
@mikesherov Thoughts on this? Looks reasonable to me.

**Comment by mikesherov** [comment]
Yes, reasonable. Feel free to submit a PR that moves gaurdedHandlers to deprecated.

**Comment by RReverser** [comment]
`guardedHandlers` itself is already in `deprecated`, and only empty case is not removed in `spec`, so here it is: #48
