### ISSUE TITLE
Supporting Stage 3 Features

### ISSUE THREAD

**Issue by bradzacher** [estree/estree#240]
I just wanted to start a discussion around the philosophy of this project to only officially support Stage 4 features.

I fully understand the reason behind only supporting Stage 4 features:
As listed in the [TC39 process document](https://tc39.es/process-document/), a Stage 3 feature may experience "Limited Post-Acceptance Changes Expected: only those deemed critical based on implementation experience".
If one of these critical changes causes a syntax change, then it means a breaking change in ESTree (which has no versioning, so handling that will be very `undefined`).

However - I would question the likelihood that a Stage 3 feature has a change that requires a change in the AST. By the time a feature reaches Stage 3:
- it's been through many months of iteration and review
- there's a general expectation that there is already a spec-complaint implementation of the feature

Which means (from my understanding) that it's very unlikely that the feature would undergo syntax changes - it's more likely that the feature would undergo changes in its implementation details.

The reason that I bring this up is because, by-and-large, the JS tooling ecosystem is converging on Stage 3 as being the minimum stable stage for implementation.

By not supporting Stage 3, it means tools like eslint cannot support it by default - leading to a non-trivial number of users that opt-in to using a 3rd-party parser which supports the newer syntax.

This also leads the ESTree ecosystem into a difficult position - how do you support Stage 3 features?
Generally this means that "the biggest project" moves to implement it, and everyone follows suit to match their AST for compatibility.
But this leads projects into issues if this AST does not match the final implementation.

Two recent examples: optional chaining and class features. For both of these the ecosystem converged on babel's AST.
- For optional chaining - an entirely different AST structure was specced for ESTree - which was a large breaking change for implementors of babel's AST.
- For class features - it's not yet a "stable" ESTree AST as it's stage 3, but the [experimental AST that's currently merged](https://github.com/estree/estree/blob/390a050fd2d6a7b69688f1434e0929d7c7455d05/experimental/class-features.md) has different naming to babel's AST (`ClassProperty -> PropertyDefinition`) and also some minor structure changes (`PrivateName -> PrivateIdentifier`).

These breakage causes *huge* pains both for maintainers and for users:
- parser maintainers have to scramble to release major version bumps to support the new AST to help the ecosystem move forward.
- eslint plugin maintainers have to make a choice about when / how to support the new AST
  - this can be non-trivial when 
- users have to navigate the fragmented ecosystem to figure out which module works with what version and how to piece it all together.
  - this is made more difficult if modules are not well maintained, as it can force users to stay on old versions of parsers and the like in order to support other parts of their toolchain.

Related: https://github.com/estree/estree/issues/228

---

The reason I bring this up is because of class features. For @typescript-eslint I would love to add full support for them, but I'm unwilling to do so because of the aforementioned breaking changes.
- If I go with the current ecosystem and implement babel's AST, then I will be forced to undergo a breaking change similar to the one I went through with optional chaining (it was *super* painful).
- If I go with the experimental ESTree AST, there's currently no guarantee that this is the final AST shape - so it's no better than the babel AST in regards to breaking changes.
  - However if I go with this AST before anyone else in the ecosystem - then it means I'll break compatibility with the ecosystem - existing plugins that only support babel's AST will no longer work.

As an implementor - this leaves me in a difficult position, and my hands are really tied. Right now the status of class features is "it will parse without error but the AST is undefined". It's really hard to convey all the nuance and reasoning behind this to users - and ultimately they just see it as broken.

**Comment by nzakas** [comment]
I think you may be misunderstanding how this project works. ESLint, as a project, only supports stage 4 features; ESTree doesn’t have that requirement.

The mess with optional chaining is what caused us to redefine how the ESTree project works. We have representatives from Acorn, Babel, and ESLint leading the spec, so there will be more alignment going forward than there was in the past.

Babel always starts on new features first as tooling to try out experimental features. They now submit their AST proposals to ESTree early on, and when the ECMA-262 features are stable, we finalize the AST format (which is often the same as the original proposal if not slightly different).

I’m not 100% sure, but I think the problem you’re looking to address has already been solved. Am I missing something?

**Comment by bradzacher** [comment]
> when the ECMA-262 features are stable

When are they considered stable? Is it stage 3? Stage 4? Some point in time between at which point you decide its stable?

> often the same as the original proposal if not slightly different

This is the part that worries me as an implementor, and was what I mentioned at the end of the OP.

If I implement the experimental AST and there is a major change "when the feature is stable" - then it will cause similar issues as if I had just gone with babel's current AST.

---

As an implementor, what I'm looking for is clearly defined guarantees that I can build on top of.

**Comment by nzakas** [comment]
Generally stage 3 is considered stable. When we think something is stable, it’s moved from the experimental folder into the main folder in one of the es* files. At that point, it’s unlikely that any further changes will take place.

unfortunately, the JS community is a bit obsessed with using unstable and unfinished features through Babel, so early adopters will always end up with tooling issues.

Again, now that the lines of communication with Babel are up, there will hopefully be less design churn as proposals are developed.

**Comment by bradzacher** [comment]
So if Stage3 is considered stable for ESTree - we can move [the "Class Features" specs from `experimental`](https://github.com/estree/estree/blob/master/experimental/class-features.md)

That's great to hear!
I can get to work on implementation for typescript-eslint!

We can close this then. That's answered my question - thanks!

**Comment by nzakas** [comment]
@bradzacher yup! Sometimes the move from experimental to final is slow (basically it's whoever has the time and interest). If you could do that, it would help move things along.

(Sorry for slow replies, my health hasn't been great lately.).

**Comment by tchetwin** [comment]
Another example: the work to update acorn's [acorn-stage3 package](https://github.com/acornjs/acorn-stage3) from the [original proposal](https://github.com/estree/estree/pull/180) to the [experimental version](https://github.com/estree/estree/blob/master/experimental/class-features.md) can be seen in these PRs:

- https://github.com/acornjs/acorn-private-class-elements/pull/16
- https://github.com/acornjs/acorn-class-fields/pull/16
- https://github.com/acornjs/acorn-private-methods/pull/6
- https://github.com/acornjs/acorn-static-class-features/pull/8
- https://github.com/acornjs/acorn-stage3/pull/11

With the alignment of `acorn-stage3` and `@typescript-eslint/parser` on the "experimental" format I would second @bradzacher's [suggestion](https://github.com/estree/estree/issues/240#issuecomment-756493286) to move class features *from* experimental.
