### ISSUE TITLE
Standardize new RegExp literal AST format

### ISSUE THREAD

**Issue by mathiasbynens** [estree/estree#27]
In Esprima, `/foo/gi` now gives:

```js
{
  type: "Literal",
  value: /foo/gi,
  regex: {
    pattern: "foo",
    flags: "gi"
  }
}
```

The advantage of having the separate `regex` property is that even in environments that don’t support a given flag (e.g. the `u` flag) the regex can still be represented in the AST. The `value` property is `null` in such a case.

See <https://code.google.com/p/esprima/issues/detail?id=557#c4>.

cc @sebmck @michaelficarra

**Comment by Constellation** [comment]
And this style can be represented as JSON.

**Comment by sebmck** [comment]
This is also the behaviour of acorn as of marijnh/acorn@f48503cd31826f8cfb0f0e2b6964879dbe318385.

**Comment by nzakas** [comment]
Espree does the same
