### ISSUE TITLE
Clearify how `BigIntLiteral.bigint` should represent

### ISSUE THREAD

**Issue by fisker** [estree/estree#296]
> `bigint` property is the string representation of the `BigInt` value. It doesn't include the suffix `n`.

https://github.com/estree/estree/blob/master/es2020.md#bigintliteral

1. Should numeric separators removed? (`1_2n`: `'12'` or `'1_2'`?)
2. Should it covert to 10-based? (`0xffn`: `'0xff'` or `'255'`?)
3. Should it be lowercased? (`0XaAn`: `'0xaa'` or `'0XaA'`?)

**Comment by bradzacher** [comment]
The times I've implemented this I have done it as just (1) - the base 10 representation of the bigint with no separators and no trailing `n`.

Essentially I've just done `bigint = node.value.toString()`

IIRC there is the `raw` property which can be used to represent the bigint literal the way it was written.

**Comment by fisker** [comment]
Remember https://github.com/typescript-eslint/typescript-eslint/pull/2067?
Environments may not support `BigInt`, then there is no `.value`.
Environments may also support `BigInt`, but don't support numeric separators.

**Comment by nzakas** [comment]
I believe the intent is that it can appear exactly as it does in the source code because it is likely to be passed to `BigInt()`, which will properly parse into a bigint value.

**Comment by bradzacher** [comment]
The bigint literal syntax allows a wider array of values than `BigInt()`:

```ts
1n;                // valid literal
BigInt('1n');      // syntax error - Cannot convert 1n to a BigInt

1_1_1n;            // valid literal === 111n
BigInt('1_1_1n');  // syntax error - Cannot convert 1_1_1n to a BigInt
BigInt('1_1_1');   // syntax error - Cannot convert 1_1_1 to a BigInt
```

So you cannot include the underscores, nor can you include the trailing `n`.

> .raw is not in ESTree spec.

That's so weird that it's not officially part of the spec given that every ESTree parser emits it (tested acorn, espree, babel, typescript-eslint).

Perhaps that's something we should get added? I'm sure there's countless eslint rules that specifically rely on `.raw` existing.
I can see ESLint core itself relies on the property existing in a few dozen cases eg:
- https://github.com/eslint/eslint/blob/b3a08376cfb61275a7557d6d166b6116f36e5ac2/lib/rules/no-loss-of-precision.js#L44-L46
- https://cs.github.com/eslint/eslint?q=%22.raw%22

---

Based on testing in ast-explorer - from what I can see it's pretty standard that parsers will treat `bigint` as "the valid string you can pass to the `BigInt()` constructor to create the bigint value" (i.e. - no underscores and no trailing `n`)

**Comment by nzakas** [comment]
Thanks for testing all of that out.

> Based on testing in ast-explorer - from what I can see it's pretty standard that parsers will treat bigint as "the valid string you can pass to the BigInt() constructor to create the bigint value" (i.e. - no underscores and no trailing n)

This seems reasonable to me. 

IIRC, `.raw` was supported in Esprima but wasn't supported in SpiderMonkey, and rather than trying to get SpiderMonkey to add it, we just omitted it from the documentation. Probably worth noting that there are non-JS parsers that implement ESTree, as well, and the documentation was meant to apply to all of the parsers.
