### ISSUE TITLE
Acorn: AssignmentPattern/RestElement vs Esprima: defaults/rest

### ISSUE THREAD

**Issue by sebmck** [estree/estree#3]
Currently acorn uses `AssignmentPattern` and `RestElement` while esprima uses a `defaults` array and `rest` property.

```javascript
function foo(bar = "", ...items) {}
```

**Esprima**

```javascript
{
  type: "FunctionDeclaration",
  params: [{ type: "Identifier", name: "bar" }],
  defaults: [{ type: "Literal", value: "" }],
  rest: { type: "Identifier", name: "items" },
  body: {
    type: "BlockStatement",
    body: []
  }
}
```

**Acorn**

```javascript
{
  type: "FunctionDeclaration",
  params: [
    {
      type: "AssignmentPattern",
      left: { type: "Identifier", name: "bar" },
      right: { type: "Literal", value: "" }
    },
    {
      type: "RestElement",
      argument: { type: "Identifier", name: "items" }
    }
  ],
  body: {
    type: "BlockStatement",
    body: []
  }
}
```

I had to adapt 6to5 to the acorn behaviour and I must say in my opinion it makes it far easy to work with.

 - https://github.com/marijnh/acorn/issues/182
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1093504

**Comment by RReverser** [comment]
@sebmck Should we extend this issue to cover binding pattern defaults and rest element in general or should it be separate one? (Esprima doesn't seem to support `ArrayPattern` / `ObjectPattern` yet)

**Comment by Swatinem** [comment]
Treating those the same would be good.

**Comment by mikesherov** [comment]
@sebmck, what's the output of both of there's a third parameter in front that doesn't have a default?

**Comment by sebmck** [comment]
@mikesherov Do you mean like:

```javascript
function foo(first, bar = "", ...items) {}
```

**Comment by mikesherov** [comment]
@sebmck, yes.

**Comment by sebmck** [comment]
```javascript
function foo(first, bar = "", ...items) {}
```

**Esprima**

```javascript
{
  type: "FunctionDeclaration",
  params: [
    { type: "Identifier, name: "first" },
    { type: "Identifier", name: "bar" }
  ],
  defaults: [
    undefined,
    { type: "Literal", value: "" }
  ],
  rest: { type: "Identifier", name: "items" },
  body: {
    type: "BlockStatement",
    body: []
  }
}
```

**Acorn**

```javascript
{
  type: "FunctionDeclaration",
  params: [
    { type: "Identifier, name: "first"  },
    {
      type: "AssignmentPattern",
      left: { type: "Identifier", name: "bar" },
      right: { type: "Literal", value: "" }
    },
    {
      type: "RestElement",
      argument: { type: "Identifier", name: "items" }
    }
  ],
  body: {
    type: "BlockStatement",
    body: []
  }
}
```

**Comment by RReverser** [comment]
@mikesherov So yes, this structure is backward compatible for ES5-only functions (those without default and rest parameters), and at the same time ES5-only AST processor will not erroneously ignore extra `defaults` and `rest` properties and so transform `function (...rest) { ... }` just like `function (rest) { ... }`, but will get early error instead, which will help to identify unsupported syntax.

This also allows to reuse and share any code from `ArrayPattern`s for function params.

**Comment by mikesherov** [comment]
Yeah, I mean that makes sense to me, although I'm essentially the layman facilitator here.

I suppose @jeffmo, @nzakas, and @ariya would like to weigh in as primary authors of Esprima and its forks.

**Comment by ariya** [comment]
Esprima (only in the experimental harmony branch, not the official master) tries to closely follow the existing output from SpiderMonkey.

Example 1: 

```js
function foo(bar = "", ...items) {}
```

Output from SpiderMonkey `Reflect.parse`:

```json
{
  "type": "Program",
  "body": [
    {
      "type": "FunctionDeclaration",
      "id": {
        "type": "Identifier",
        "name": "foo"
      },
      "params": [
        {
          "type": "Identifier",
          "name": "bar"
        }
      ],
      "defaults": [
        {
          "type": "Literal",
          "value": ""
        }
      ],
      "body": {
        "type": "BlockStatement",
        "body": []
      },
      "rest": {
        "type": "Identifier",
        "name": "items"
      },
      "generator": false,
      "expression": false
    }
  ]
}
```

Example 2:

```js
function foo(first, bar = "", ...items) {}
```

Output from SpiderMonkey `Reflect.parse`:

```json
{
  "type": "Program",
  "body": [
    {
      "type": "FunctionDeclaration",
      "id": {
        "type": "Identifier",
        "name": "foo"
      },
      "params": [
        {
          "type": "Identifier",
          "name": "first"
        },
        {
          "type": "Identifier",
          "name": "bar"
        }
      ],
      "defaults": [
        {
          "type": "Literal",
          "value": ""
        }
      ],
      "body": {
        "type": "BlockStatement",
        "body": []
      },
      "rest": {
        "type": "Identifier",
        "name": "items"
      },
      "generator": false,
      "expression": false
    }
  ]
}
```

**Comment by RReverser** [comment]
Yes, `AssignmentPattern` / `RestElement` were agreed later following the email discussion initiated by @Swatinem and exist as bug in SpiderMonkey tracker (see issue description for link). Would be nice to standardize those in ESTree as well, as benefits seem to be clear, and if we do it now (when ES6 AST is not stabilized), it will break less tools.

**Comment by nzakas** [comment]
I'd love to get this squared away soon...we were planning on shipping rest args in ESLint very soon, and I'd like to be sure we're using whatever the final agreement is.

**Comment by mikesherov** [comment]
Seems like both SpiderMonkey and Esprima match here, but seems Acorn's solution is more robust. @dherman, thoughts from SpiderMonkey's perspective here?

@nzakas, if you guys aren't afraid of major version bumps in espree, I'd say ship as is for now, and possibly break this in the next major version if both SpiderMonkey and Esprima agree to switch?

**Comment by sebmck** [comment]
@mikesherov AFAIK Spidermonkey is planning to ship this (@dherman can confirm) and that was the only reason the behaviour of acorn was implemented in the first place.

**Comment by mikesherov** [comment]
Ok, if we can get confirmation from @dherman, I'll make sure we have a good answer here tomorrow after the Esprima team meeting.

**Comment by nzakas** [comment]
@mikesherov breaking changes are a lot harder for us due to the third party plugins ecosystem of ESLint (not just public, a lot of companies have internal rules, too). I'd rather hold off on introducing something of it's just going to change in the future. The good thing about Espree feature flips is I can force a feature off without removing it.

**Comment by mikesherov** [comment]
@sebmck, we ran out of time in the meeting, and would love confirm from @dherman, because I think that was @ariya's main objection.

**Comment by ikarienator** [comment]
Honestly I think acorn's way of handling default parameter is a better solution, although `AssignmentPattern` sounds a little bit off.

In the spec, a parameter of a function-like is a `BindingElement`, which is a "simple pattern" (identifier or object pattern or array pattern) , followed by a optional `initializer` to indicate default value. `BindingElement`s are used inside the array patterns and object patterns as well, so making a special case for function parameter does not really make sense. By the end of the day, you can represent parameter/array pattern elements without default as the old style expression and use a `"BindingWithDefault"` type node to combine the default value.

For the rest parameter, again the spec use symbol `BindingRestElement` for rests used in function-likes and array patterns. It also make sense to have its own type. But as a nerd, I'm a little resistant on puting `BindingRestElement`s together with other binding elements in a list because they only show up at the end of the list and exactly zero or one time. Also, it can only be an identifier, we shall simply use an `Identifier?` at that position. I would like to design it like:

```js
function foo(first, bar = "", ...items) {}
```

```js
{
  type: "FunctionDeclaration",
  params: [
    { type: "Identifier", name: "first" },
    {
      type: "BindingWithDefault",
      binding: { type: "Identifier", name: "bar" },
      init: { type: "Literal", value: "" }
    }
  ],
  rest: { type: "Identifier", name: "items" },
  body: {
    type: "BlockStatement",
    body: []
  }
}
```

```js
function a({a, b=3, c:d=4, j: {k} = {k:1}, [0]:x=-1}, [e,/*elided*/,f=5,...g]=0, h, ... i) {}
```

```js
{
    type: "FunctionDeclaration",
    params: [
        {
            type: "ObjectPattern",
            properties: [{
                shorthand: true,
                computed: false,
                key: null,
                binding: {type: "Identifier", name: "a"}
            }, {
                shorthand: true,
                computed: false,
                key: null,
                binding: {
                    type: "BindingWithDefault",
                    binding: {type: "Identifier", name: "b"},
                    init: {type: "Literal", value: 3}
                }
            }, {
                shorthand: false,
                computed: false,
                key: {type: "Identifier", name: "c"},
                binding: {
                    type: "BindingWithDefault",
                    binding: {type: "Identifier", name: "d"},
                    init: {type: "Literal", value: 4}
                }
            }, {
                shorthand: false,
                computed: false,
                key: {type: "Identifier", name: "j"},
                binding: {
                    type: "BindingWithDefault",
                    binding: {
                        type: "ObjectPattern",
                        properties: [{
                            shorthand: true,
                            computed: false,
                            key: null,
                            binding: {type: "Identifier", name: "k"}
                        }]
                    },
                    init: {
                        type: "ObjectExpression",
                        properties: [{
                            shorthand: false,
                            computed: false,
                            key: {type: "Identifier", name: "k"},
                            binding: {type: "Literal", value: 1}
                        }]
                    }
                }
            }, {
                shorthand: false,
                computed: true,
                key: {type: "Literal", value: 0},
                binding: {
                    type: "BindingWithDefault",
                    binding: {type: "Identifier", name: "x"},
                    init: {type: "Literal", value: -1}
                }
            }]
        }, {
            type: "ArrayPattern",
            elements: [
                {type: "Identifier", name: "e"},
                null,
                {
                    type: "BindingWithDefault",
                    binding: {type: "Identifier", name: "f"},
                    init: {type: "Literal", value: 5}
                }
            ],
            rest: {type: "Identifier", name: "g"}
        }, {
            type: "BindingWithDefault",
            binding: {type: "Identifier", name: "bar"},
            init: {type: "Literal", value: ""}
        },
        {type: "Identifier", name: "h"}
    ],
    rest: {type: "Identifier", name: "i"},
    body: {
        type: "BlockStatement",
        body: []
    }
}
```

Also, if there is no default value of the parameters in function-likes, the `default` array is weirdly set to `[]` instead of having many `null`s. The design above also avoid this inconsistencies.

SPEC: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns

**Comment by mikesherov** [comment]
After discussing in the esprima meeting, we're ok moving forward in Acorn's direction here to achieve interop, assuming SM will move that way too.

That means we need a signal from @dherman here that SM will move that way, and we should be good to go!

**Comment by RReverser** [comment]
@mikesherov That's a great news! I really like this ESTree initiative more and more, things are getting agreed between different participants much faster than earlier.

**Comment by benjamn** [comment]
Shouldn't we be modifying fields of the `Function` supertype, rather than `FunctionDeclaration`?

**Comment by mikesherov** [comment]
@benjamn this change is to remvoe the `rest` parameter from all `function`s, yes. Is that not clear from the conversation / description?

**Comment by benjamn** [comment]
The intent is pretty clear, sure, but this seems like a good place to talk in terms of the type specification, rather than just giving examples of input/output.

**Comment by benjamn** [comment]
Just out of curiosity, what is `(function(...rest){}).length` supposed to be?

**Comment by RReverser** [comment]
`0` (zero) as far as I remember spec.

**Comment by RReverser** [comment]
Same for `function(x = 1, y = 2, ...rest)`.

**Comment by fkling** [comment]
> Just out of curiosity, what is `(function(...rest){}).length` supposed to be?
> `0` (zero) as far as I remember spec.
> Same for `function(x = 1, y = 2, ...rest)`.

Yep. For reference: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions-static-semantics-expectedargumentcount
