### ISSUE TITLE
Shift initiative

### ISSUE THREAD

**Issue by Victorystick** [estree/estree#30]
I'm interested in the groups opinion on the [Shift AST](https://github.com/shapesecurity/shift-spec), which is heavily influenced my SpiderMonkey but breaks compatibility by reducing the number of invalid programs that the AST may represent.

I wonder if the goal of ESTree is simply to have the community standardize the SpiderMonkey AST, our if it aims to address issues and build a refined and more convenient AST for ECMAScript tooling.

**Comment by michaelficarra** [comment]
See https://twitter.com/jspedant/status/567037276450848768.

> Note that this is not a "new" standard, but simply the original SpiderMonkey standard (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) now on Github. The Github discussion is meant to standardise previously unspecified ES6 nodes in the SpiderMonkey format. Also, it will be the ultimate source of truth for when SpiderMonkey's Reflect.parse differs from what is specified on MDN.

As I understand it, we are not interested in making backwards-incompatible changes. If someone wants to go through and update every tool to support a backwards-incompatible change to the SpiderMonkey AST, I see no reason why they wouldn't just switch to the Shift AST.

<sub>*Full disclosure: I helped create the Shift AST, but I am trying to be as impartial as possible in these discussions. I know SpiderMonkey-based tools are not going away any time soon.*</sub>

**Comment by RReverser** [comment]
Yes, the goal of this spec is to be living SpiderMonkey-compatible standard for AST forms of new syntax features and not to create another own standard.

So I guess we can close this issue.
