### ISSUE TITLE
[ES6] TemplateLiteral

### ISSUE THREAD

**Issue by ikarienator** [estree/estree#34]
## SPEC:
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literals

We need to represent both "tagged" or "untagged" template literals.

For example:

```es6
raw`x${y}z`
```

should have:

0. `raw` as an expression
0. `x` as a template literal element
0. `y` as an expression
0. `z` as a template literal element

### SpiderMonkey Parser API:
Not implemented

### Esprima-harmony:
```webidl
interface TemplateElement <: Node {
  type = "TemplateElement",
  value: {
    raw: string,
    cooked: string
  },
  tail: boolean
}

interface TemplateLiteral <: Expression {
   type = "TemplateLiteral",
   expressions: [Expression],
   quasis: [TemplateElement]
}

interface TaggedTemplateExpression <: Expression {
  type = "TaggedTemplateExpression",
  tag: Expression,
  quasi: TemplateLiteral
}
```

### Acorn:
Same as Esprima-harmony

### Shift-API:
Kinda bad naming...
```webidl
interface TemplateString : Expression {
  attribute Expression? tag;
  attribute (Expression or TemplateLiteral)[] elements;
};

interface TemplateLiteral : Node {
  attribute string value;
}
```

**Comment by sebmck** [comment]
I take it you missed #25?

**Comment by ikarienator** [comment]
I did...
