### ISSUE TITLE
About correctness: let+const VariableDeclaration vs Statement

### ISSUE THREAD

**Issue by fkling** [estree/estree#40]
Sorry if this was already discussed, I couldn't find anything about it.

Currently a `Declaration` is a `Statement`, and  `VariableDeclaration` is extended to represent `let` and `const` as well:

```js
interface Declaration <: Statement { }

interface VariableDeclaration <: Declaration {
    type: "VariableDeclaration";
    declarations: [ VariableDeclarator ];
    kind: "var";
}

extend interface VariableDeclaration {
    kind: "var" | "let" | "const";
}
```

That allows the following AST (or similar), which is not a valid JS program:

```js
 // if (x) let y = 42;
{
  "type": "IfStatement",
  "test": {...},
  "consequent": {
    "type": "VariableDeclaration",
    "declarations": [...]
    "kind": "let",
  },
  "alternate": null,
}
```

But of course a parser could easily detect this and throw accordingly.

I am trying to get an idea about the direction/principles of estree. Is a simple API favored over correctness/spec compliancy and is correctness offloaded to parser implementations?

Or is this something that should be fixed?

**Comment by RReverser** [comment]
> correctness offloaded to parser implementations

Yes, like that. In fact, there's a lot of things that are not valid executable JavaScript, but can be represented by AST, and it's not data structure's responsibility to response for semantic stability, but rather to give simple structured representation of any code that can be generated and consumed by tools.

**Comment by fkling** [comment]
Thanks for clarifying!

**Comment by michaelficarra** [comment]
@fkling:

> there's a lot of things that are not valid executable JavaScript, but can be represented by AST

This is one of the major motivations behind the design of [the Shift AST format](http://engineering.shapesecurity.com/2014/12/announcing-shift-javascript-ast.html). If that's what you're looking for, you should look into using the Shift format instead. I've compiled a [list of similar problems throughout the SpiderMonkey AST format](http://engineering.shapesecurity.com/2015/01/a-technical-comparison-of-shift-and.html).
