### ISSUE TITLE
Add flag on Program node to indicate module code?

### ISSUE THREAD

**Issue by nzakas** [estree/estree#46]
It would be nice to be able to tell if a given Program represents module code or not. The Shift AST actually has two different nodes `Script` and `Module` to represent the source type. It's probably too big of a change to go for a separate node in ESTree, however, what about a property on `Program`? Maybe `sourceType` as "script" or "module"?

**Comment by RReverser** [comment]
How do you want to tell `script` from `module`? If it's an individual option passed to parser itself, then there's not much sense in including this info in returned node. Or do you want some intelligence based on existance of `export` nodes in code?

**Comment by nzakas** [comment]
You're assuming that the code calling the parser and the code evaluating the AST are close to each other. Any utility that works on a passed-in AST would benefit from knowing if a script was parsed in a module context. 

The big difference is that module code runs in strict mode, and that is true whether or not `export` is used.

**Comment by RReverser** [comment]
Strictness is something that should be handled on parsing stage, so parser can determine it internally from passed options + directives and either return valid AST or throw error depending on rules.

**Comment by michaelficarra** [comment]
@RReverser Strict mode code has different runtime behaviour. We designed the Shift AST this way because we cannot afford to lose that information.

**Comment by RReverser** [comment]
As for AST tools, runtime behavior matters only for transpiler I guess, which usually parses code on its own, but I see your point, might make sense to include it.

Btw, just an idea - but why not include `strict` boolean to `Program` and `Function` nodes instead so that they could be easily passed around without losing strictness state? I.e. if function was initially strict because it was defined inside another strict program/function (either via parsing mode or directive), it should be possible to extract it's node and put it in non-strict context without losing inner strictness of function itself.

**Comment by nzakas** [comment]
Having a `strict` flag rather than something saying it's a module means it wouldn't be possible to validate an AST as correct (i.e., is `import` or `export` actually allowed?).

**Comment by caridy** [comment]
@RReverser modules are not just scripts in strict mode, they are much more then that. e.g.: `this` is undefined in a module body, while it is global in a script.

**Comment by RReverser** [comment]
`this` is undefined in any strict script, isn't it? For browser scripts `'use strict'` in top scope makes entire global scope strict, so global `this` becomes undefined for all the scripts, and in Node.js module is implicitly wrapped into anonymous function, so `'use strict'` in first line of module makes `this` undefined within this function (entire module).

**Comment by mikesherov** [comment]
:+1: for new property on Program Node, would be really useful for linter consumers of an AST.

As far as strict property of function node, I'm -1 on that as it presumes a single directive. Things like 'use asm' are why we have an issue open for a directive property on expressionStatement nodes.

**Comment by caridy** [comment]
@RReverser 

test.js
```javascript
"use strict";
console.log(this);
```

for that file, if you `require('./test.js')` or use `<script src="./test.js"></script>` it will log the value of global :), if that's a module, it will be `undefined`.

**Comment by sebmck** [comment]
@caridy 

> if you `require('./test.js')`

Actually in node (and other CommonJS-like environments) that'll be `exports`.

**Comment by caridy** [comment]
ha, right, `this === exports === module.exports`. But the point is that the value of `this` is not `undefined`.

**Comment by caridy** [comment]
aside from that, part of the conversation in TC29 is about how modules will allow us to innovate in the future without having to carry on with the all the baggage of the scripts. That's why we decided to set that value to `undefined` in the first place.

**Comment by RReverser** [comment]
Ah, I was dumb. Thinking about different `this`. Ok then, if tools can benefit from this extra property, then I'm definitely :+1:, just wanted to make sure we don't add extra baggage where it can be avoided.

**Comment by RReverser** [comment]
@nzakas Could you please create PR for this?

**Comment by nzakas** [comment]
Will do.
