### ISSUE TITLE
Do we need SuperExpression?

### ISSUE THREAD

**Issue by nzakas** [estree/estree#54]
For `this`, there's `ThisExpression` in the AST.

Do we need a `SuperExpression` to represent calls to `super`?

**Comment by RReverser** [comment]
Might be useful IMO.

**Comment by michaelficarra** [comment]
We have a `Super` node in the Shift AST, which we use to restrict `super` from anywhere but the `object` of a `MemberExpression` and the `callee` of a `CallExpression`. I think that design is best, but I don't feel the estree effort should be trying to standardise something other than what the current SpiderMonkey format parsers already agree upon. If they didn't already agree, I could support this.

**Comment by RReverser** [comment]
It was rather not an agreement, but kind of "accidental" parsing as-is, since any unknown identifier-like set of chars is parsed, well, as identifier, and `super` matched this perfectly. However, having a special type for it might be useful for AST consumers.

**Comment by mikesherov** [comment]
I think for tools that do scope analysis etc, we should consider this. As @RReverser said, the lack of `SuperExpression` is simply an accident. @ariya, @sebmck, thoughts?

**Comment by sebmck** [comment]
@mikesherov Yeah this seems practical, would make a lot of things easier, especially when `super` is meant to be parsed differently.

**Comment by ariya** [comment]
@dherman Is SM going to change to account for `SuperExpression`?

**Comment by efaust** [comment]
Hey, I'm the dev doing classes in SM. I can change our reflection API to match whatever we need. We currently have a separate node in our AST, but reflect it as a MemberExpression, as was done previously by esprima. Any other design is equally doable, if that is preferred.

**Comment by RReverser** [comment]
@ariya What would you say?

**Comment by michaelficarra** [comment]
I just want to remind everyone that if we introduce a node for this, it should be `Super`, not `SuperExpression`, and only allowed in the two positions I mentioned above.

**Comment by ariya** [comment]
+1 for `Super` (instead of `SuperExpression`)

**Comment by sebmck** [comment]
Hold up, before we merge are we sure we don't want `SuperProperty` and `SuperCall`?

**Comment by RReverser** [comment]
@sebmck I just need to ask - are you serious about that?

**Comment by sebmck** [comment]
@RReverser Yes and no. `super` is only allowed in those two scenarios and just want to make sure we've got all our bases covered so in the future noone complains about not taking everything into consideration.

**Comment by mikesherov** [comment]
@efaust please note this has now been merged.
