### ISSUE TITLE
Extend ExpressionStatement to indicate a directive prologue

### ISSUE THREAD

**Issue by mikesherov** [estree/estree#6]
In the current syntax tree, a directive such as `"use strict"` will appear as `ExpressionStatement`. A tool that consumes the tree and needs to be aware of the strict mode will have to perform an extra step to figure out whether such an ExpressionStatement is representing a directive or not.

In this proposal, a new flag `directive` is added to `ExpressionStatement`. The value is the representation of the directive prologue in the source text.

The current state:

```
> esprima.parse('"use strict"').body[0]
{ type: 'ExpressionStatement',
  expression: 
   { type: 'Literal',
     value: 'use strict' } }
```

If this proposal is implemented, it becomes:

```
> esprima.parse('"use strict"').body[0]
{ type: 'ExpressionStatement',
  expression: 
   { type: 'Literal',
     value: 'use strict', },
  directive: 'use strict' }
```

Additional resources:
- ECMAScript 5.1 [Section 14.1](http://es5.github.io/#x14.1) on _Directive Prologues and the Use Strict Directive_
- Previous Esprima discussion: https://code.google.com/p/esprima/issues/detail?id=330.
- SpiderMonkey issue: https://bugzilla.mozilla.org/show_bug.cgi?id=791294
- See discussion on jquery/esprima#1006 for more information

**Comment by michaelficarra** [comment]
A few corrections:

* the `raw` value is a non-standard esprima extension, and should not be included here
* the `directive` value must be the representation in the source code; a Boolean is not sufficient
* the `directive` value could be on either the `ExpressionStatement` or the `Literal`; they both have drawbacks

See discussion on jquery/esprima#1006 for more information.

**Comment by mikesherov** [comment]
@michaelficarra corrected... thanks!

**Comment by michaelficarra** [comment]
> The value is set to `true` for a directive prologue.

Should be replaced with

> The value is the representation of the directive prologue in the source text.

**Comment by mikesherov** [comment]
Gah. Got it.

**Comment by sebmck** [comment]
> the `raw` value is a non-standard esprima extension, and should not be included here

TIL. Should it be standardised?

**Comment by mikesherov** [comment]
@sebmck file an issue?

**Comment by michaelficarra** [comment]
@sebmck: What value does it have? Remember, ASTs don't have to be created by a parser.

**Comment by sebmck** [comment]
@michaelficarra Yeah that's true. Can a wiki page be made on jquery/esprima for things like this?

**Comment by mikesherov** [comment]
@sebmck stub page made: https://github.com/jquery/esprima/wiki/Deviations-from-ESTree

**Comment by sebmck** [comment]
@mikesherov Thanks!

On Friday, 13 February 2015, Mike Sherov <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> stub page made:
> https://github.com/jquery/esprima/wiki/Deviations-from-ESTree
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/6#issuecomment-74163457>.
>


-- 
Sebastian McKenzie

**Comment by dherman** [comment]
@michaelficarra I think the `raw` property merits a discussion but I'll pull it out into a separate issue.

**Comment by dherman** [comment]
Sounds like everyone's on board for the backwards-compatible solution (as opposed to a new PrologueDirective node)? I'll PR it.

**Comment by ikarienator** [comment]
A `Literal` without a `raw` field cannot help to determine if it's a use-strict directive.

**Comment by mikesherov** [comment]
I'll whip up a new PR for this.

**Comment by sebmck** [comment]
What about a `directives` property on `BlockStatement` (or `Function`) and `Program`? It'd make it **far** easier to consume (and transform which is obviously my main motivator :stuck_out_tongue:) and I'm not entirely sure how helpful adding it to `ExpressionStatement` (or `Literal`) is.

**Comment by michaelficarra** [comment]
That doesn't sound like a very good idea. Do you then drop the `ExpressionStatement`s that currently represent directives from the parse tree? If not, do they have to be in sync?

**Comment by sebmck** [comment]
@michaelficarra Nope, they'd still be in the AST. What do you mean by in sync? Seems more useful to have it on the parent since you're still going to need to crawl the body for directives in the first place so I'm questioning the benefit of it in the first place.

**Comment by michaelficarra** [comment]
I'm saying that structure allows for a function/script that claims it has a directive, but then the body contains ExpressionStatements that could not possibly represent that directive (or no ExpressionStatements at all). Also, I would imagine we would want to omit the ExpressionStatement nodes because, if we don't, we'd still need to be able to distinguish directives from string literals in statement position.

**Comment by gibson042** [comment]
We've seen a lot of pressure to preserve concrete elements that are discarded in the conversion from input code points to abstract syntax tokens... @sebmck's suggestion comes from the other side, requesting information that is derived from an AST and affects its associated semantics. As such, I think it belongs in a separate issue... this one relates to accurately _representing_ syntax, not interpreting it.

**Comment by ariya** [comment]
@mikesherov Do you have a PR ready for this?

**Comment by mroch** [comment]
As of https://github.com/facebook/flow/commit/5e55038ae2a739dc61285321f308b157f4e20746, the flow parser also adopts the proposal from https://github.com/estree/estree/pull/99, like esprima did in https://github.com/jquery/esprima/issues/1281

**Comment by RReverser** [comment]
@mroch That Esprima PR you linked was closed, not merged.

**Comment by danez** [comment]
@RReverser It was merged later: https://github.com/jquery/esprima/pull/1453

**Comment by mikesherov** [comment]
@RReverser @hzoo @ariya can we move forward on this? Does Acorn's or Babylon's impl match esprima here?

**Comment by ariya** [comment]
👍  from me

**Comment by RReverser** [comment]
@mikesherov If you mean https://github.com/estree/estree/pull/99 PR then at least it should address the quotes comment from @gibson042. Also, while I'm pro-distinguishing directives from everything else, I'm somewhat concerned about duplication between `ExpressionStatement.directive`, `Literal.value` and de-facto standard `Literal.raw` on such values - too easy to get them all out of sync.

**Comment by danez** [comment]
In the implementation of esprima, quotes are not included and I implemented it the same way in babylon (raw value without quotes). Also flow has it done [this way](https://github.com/facebook/flow/commit/5e55038ae2a739dc61285321f308b157f4e20746#diff-28ec51deee60be34ab9451f52d6a1f5dR489) I think, but I'm not an expert in ocaml.

@mikesherov @RReverser Should I make a new PR with the wording about quotes changed?

I don't have a better idea about the distinguish problem, just wanted to throw in that babylon, by default adds a new field `directives` on `Program` on `BlockStatement` which contains [`Directive`](https://github.com/babel/babylon/blob/master/ast/spec.md#directive) nodes and does not add the Statement to the `body`. For printing we simply first print all `directives` and then the `body`, but I see that this possibility was already sorted out above for (valid) reasons.

**Comment by mikesherov** [comment]
@rreverser, I can take #99 over and address the quotes issue. Are you ok without moving forward despite the concern of values possibly getting out of sync if one isn't careful?

**Comment by mikesherov** [comment]
@danez, actually go ahead and draft that new PR please.

**Comment by RReverser** [comment]
@mikesherov That kind of contradicts '3. Unique' from our README, so if there's a better way, I would love to go with it, but not sure yet what it would look like.

**Comment by mikesherov** [comment]
@RReverser I can see your argument about unique, but I've always interpreted that as duplication at the node level. I do believe this deserves a special case, as it's a natural consequence of directives being located in the body of the construct they are affecting. Discerning strictness otherwise is not straightforward, and you're essentially stuck redoing work the parser/code generator already had to do to generate the AST in the first place.

Also, consider the use cases for this directive property, I can't think of a transform being done that would cause these to get out of sync. I'm legitimately curious... can you?

Re: what it would look like: I think you're either stuck with traversing the function body, or having a bit of duplicate data.

**Comment by RReverser** [comment]
@mikesherov The dangerous use case I'm thinking about is inserting new statements to the beginning of function (this is a problem even in current representation) as inserting another statement before the `ExpressionStatement(Literal)` effectively makes it non-directive, while the `directive` property will persist.

In most cases you would want to have these directives in a separate array in order to make sure you're not making functions less strict / non-asmjs-ish etc., but I guess that would be a breaking change?

**Comment by mikesherov** [comment]
Right. Too much breaking change. Needs to be additive as per principle 1. Additive and not duplicative conflict occasionally, like in this case.

This change or not, transformers need to be aware of directives and not stomping on them. Much easier to check if strict, and insert at statement 1 vs 0 then having to determine strictness first, then decide whether to insert at 1 or 0

**Comment by mikesherov** [comment]
@RRreverser can we move forward on this as is?
