### ISSUE TITLE
Define spec in JSON or other format

### ISSUE THREAD

**Issue by gkz** [estree/estree#60]
Instead of simply defining the spec in Markdown documents, it could be defined in JSON or another format. The Markdown documents could be generated from this data.

- Tools could easily consume the spec
- The spec used by tools and the written spec would never diverge
- Tools could automatically be tested against the spec, without having to write separate tests
- All nodes, whatever the ES version, could be included, and different spec documents for ES5, ES6, etc. could be generated automatically 
- Varying documentation could be generated based off of the data, eg. maybe spec.md doesn't need to display any examples, but for online documentation, they could be included

Eg.
```
{
    "IfStatement": {
        "properties": {
            "test": "Expression",
            "consequent": "Statement",
            "alternate": "Statement | null"
        },
        "es": 1,
        "syntax": "if ($test) $consequent [else $alternate]",
        "description": "An `if` Statement",
        "example": "if (x) { foo(); }"
    },
    ...
}
```

I am currently using my own (outdated, not yet updated for ES6) version of something like this for my tool http://www.graspjs.com/ for both traversal, syntax of query languages, and documentation. It would be nice, for me and other tool creators, to simply be able to link to the spec and always to up to date (along with the other benefits I listed above).

**Comment by RReverser** [comment]
I actually thought about the opposite way - extracting interfaces from current documents and generating other formats, so that spec remains human-readable and -writable. Going to experiment with that soon.

**Comment by nzakas** [comment]
I'm more in @RReverser's camp here. We need the thing we edit to be human-friendly (JSON is not) and then be able to create other formats from the human-friendly version.

**Comment by getify** [comment]
+1 @nzakas @RReverser i would definitely like the JSON version, but it doesn't need to originate in that format.

**Comment by gkz** [comment]
Good idea, I hadn't thought about generating it the other way. As long as a JSON version can be consistently produced, it doesn't matter which way we go.

**Comment by RReverser** [comment]
Sure, I'm going to get to this in a few days. I already had parsing + generating TypeScript defs on my list, and generating JSON would be even easier.

**Comment by impinball** [comment]
Would it be possible to rewrite this in full IDL?

**Comment by mikesherov** [comment]
I'm with @impinball here. IDL seems like the way to go.

**Comment by ikarienator** [comment]
BTW, Shift have a brittle IDL subset parser: https://github.com/shapesecurity/shift-spec/blob/es6/src/generate-spec.js

**Comment by impinball** [comment]
If we do actually go the IDL route, it would be easiest to go with specifically the WebIDL dialect, since there are already several tools out there to parse/consume it, especially in JavaScript. It would also be easy to write an AST validator from that

**Comment by RReverser** [comment]
@gkz @nzakas @getify I've built a simple spec parser from our Markdown files and JSON generator. See [code](https://github.com/estree/formal/blob/master/src/index.js), [spec grammar](https://github.com/estree/formal/blob/master/src/grammar.jison) and [generated JSON files](https://github.com/estree/formal/tree/master/formal-data for sample files).

**Comment by getify** [comment]
:+1:

**Comment by nzakas** [comment]
Very cool

**Comment by RReverser** [comment]
I'm closing this as original issue (machine-readable format) is resolved now, and consequent stuff like generating other formats from it can be discussed in separate issue in `estree/formal` repo.

**Comment by RReverser** [comment]
Update: I've also managed to generate TypeScript definitions, should be merged to [DefinitelyTyped store](https://github.com/RReverser/DefinitelyTyped/blob/master/estree/estree.d.ts) soon.
