### ISSUE TITLE
AssignmentPattern is a wrong name

### ISSUE THREAD

**Issue by ikarienator** [estree/estree#62]
Today I realized that in ES6 spec we have an AssignmentPattern, and it is a totally different thing:

* `AssignmentPattern` in ES6 means the pattern that can be put on the left hand side of an "=" assignment.
* `AssignmentPattern` in estree means a [`BindingElement`](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns) that has a `Initializer`.

Furthermore, `AssignmentPattern` in estree has nothing to do with assignments, except for that we use single equal sign to denote default value, which can also be a part of an assignment...

Proposal: `{Pattern|Binding}With{Default|Init}`, `Default{Pattern|Binding}`, `Defaulted{Pattern|Binding}`...

**Comment by impinball** [comment]
Could you elaborate on your proposal?

**Comment by RReverser** [comment]
Also, don't forget that ES6 spec and ESTree spec are not related - the only thing that is common to both is language that they describe. There's a lot of other names that differ in those, as they describe very different aspects of the language, have different use-cases and tools that implement them.

**Comment by sebmck** [comment]
Just to add onto what @RReverser said, AssignmentExpression is probably the
largest offender between ESTree and the ES6 spec so there's a lot of
serious prior art.

On Monday, 6 April 2015, Ingvar Stepanyan <notifications@github.com> wrote:

> Closed #62 <https://github.com/estree/estree/issues/62>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/62#event-274195824>.
>


-- 
Sebastian McKenzie
