### ISSUE TITLE
Firefox, Safari, and Chrome all use 1-based column numbers -- estree should too

### ISSUE THREAD

**Issue by fitzgen** [estree/estree#65]
Or somehow convince everyone else to use 0-based columns (if it doesn't break the web).

**Comment by dherman** [comment]
I am pretty confident changing error stack indices would break the web.

**Comment by nzakas** [comment]
:-1: If such compatibility is an issue, it can be handled downstream by tools.

**Comment by RReverser** [comment]
@nzakas :+1: I don't see reasons to break established logic and tools that rely on it.

**Comment by mikesherov** [comment]
@fitzgen thanks for contributing! We can't break the web, so closing this issue.

**Comment by getify** [comment]
Not disagreeing with the resolution here. I also think we should leave them 0-based. Such re-mapping of line numbers or column numbers is entirely in the realm of tools and not standards. IIRC, JSLint awhile back begrudgingly added a feature to change the numbering.

But the "would break the web" assertion is not terribly obvious. I've tried for a bit to come up with many practical use-cases where that's true and I can't. We might want to add more detail here, or somewhere, to document for posterity why that would be the case.

**Comment by mikesherov** [comment]
"Break the web" is generic shorthand for "break all downstream consumers of esprima, acorn, and Spidermonkey".
