### ISSUE TITLE
Formalize SpreadElement

### ISSUE THREAD

**Issue by fkling** [estree/estree#7]
Estree currently doesn't define `SpreadElement`, which is used by esprima and acorn in `ArrayPattern`s and `ArrayExpression`s.

[Example](http://felix-kling.de/esprima_ast_explorer/#/ykp8P3Yy1c/1):

```js
// [a, ...b] = x;
{
  "type": "AssignmentExpression",
  "operator": "=",
  "left": {
    "type": "ArrayPattern",
    "elements": [{
      "type": "Identifier",
      "name": "a"
    }, {
      "type": "SpreadElement",
      "argument": {
        "type": "Identifier",
        "name": "b"
      },
    }],
  },
  "right": {
    "type": "Identifier",
    "name": "x"
  }
}
```

Edit:

I'm not suggesting/implying that it has to be `SpreadElement` or that it has to be used in both cases, just we have to properly define it (them) for `ArrayPattern`s and `ArrayExpression`s.

**Comment by RReverser** [comment]
Correction: in `ArrayPattern`s and function parameters (#3) Acorn and SpiderMonkey use `RestElement` in order to distinguish `Expression`-value from `Pattern`-binding as with other node types.

**Comment by fkling** [comment]
@RReverser: Hmm, I call `acorn --ecma6 test.js`, where `test.js` is `[a, ...b] = [x,...y];` I get a `SpreadElement` in both cases. I installed acorn from npm.

Anyway, I'm not suggesting/implying that it has to be `SpreadElement` or that it has to be used in both cases, just we have to properly define it (them) for `ArrayPattern`s and `ArrayExpression`s.

I'm actually in favor for different node types for patterns and expressions, but I don't have a profound reason for it.

**Comment by RReverser** [comment]
@fkling Oh, you're right, it's in master and 6to5's fork, but not released.
