### ISSUE TITLE
Super should not be an Expression

### ISSUE THREAD

**Issue by ikarienator** [estree/estree#71]
In fact, it should be an node and we need to extend member expression and call expression to allow `Super` at that location.

**Comment by sebmck** [comment]
See pull request #70

On Saturday, 21 March 2015, Bei Zhang - Ikarienator <
notifications@github.com> wrote:

> In fact, it should be an node and we need to extend member expression and
> call expression to allow Super at that location.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/71>.
>


-- 
Sebastian McKenzie

**Comment by michaelficarra** [comment]
@ikarienator send my branch a PR if you want that PR updated before I get back from holiday. I don't have my computer.

**Comment by ikarienator** [comment]
Sorry didn't see it. Closing this now.
