### ISSUE TITLE
Module specifiers do not inherit from Node

### ISSUE THREAD

**Issue by btmills** [estree/estree#74]
`ExportSpecifier`, `ImportSpecifier`, `ImportDefaultSpecifier`, and `ImportNamespaceSpecifier` do not inherit directly or indirectly from `Node`. Is this intentional? I looked through #11 and #35 but couldn't find any discussion to indicate that that would be the case.

I investigated and found that jquery/esprima#1149 will attach `loc` to all four node types when requested. The ast-types implementation does not have modules as they are currently specified, but it does have specifiers inherit from [an abstract `Specifier` type](https://github.com/benjamn/ast-types/blob/master/def/es6.js#L162), which itself inherits from `Node`.

**Comment by RReverser** [comment]
> Is this intentional?

No, I don't think so.

**Comment by impinball** [comment]
I apologize for that oversight (that was initially from my PR).
