### ISSUE TITLE
Destructuring assignment failed in live demo

### ISSUE THREAD

**Issue by jiyinyiyong** [estree/estree#77]
None of the folowing work at http://esprima.org/demo/parse.html
```js
[a, b] = [1, 2]
[a, b, ...rest] = [1, 2, 3, 4, 5]
{a, b} = {a:1, b:2}
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by fkling** [comment]
The last one is invalid anyway. What does problems with esprima have to do with estree?

**Comment by fkling** [comment]
FYI, [destructuring is supported in v2.2](https://github.com/jquery/esprima/issues?utf8=%E2%9C%93&q=milestone%3A2.2+), which seems to be going to be release very soon. v2.1 (what the website runs) doesn't support destructuring yet. But again, wrong repo.

**Comment by sebmck** [comment]
This is the repo for the AST spec so this is the wrong place to report this. Also as @fkling noted, the Esprima site is old.

**Comment by jiyinyiyong** [comment]
My mistake, I was checking both repo to see if it is broken. Thanks for the link of v2.2.

**Comment by getify** [comment]
> {a, b} = {a:1, b:2}
> The last one is invalid anyway, so that shouldn't "work" anyways. 

Just for posterity sake, this one is invalid when standalone (because `{a, b}` is a block, not an object), but this makes it valid:

```js
( {a, b} = {a:1, b:2} )
```
