### ISSUE TITLE
Module declarations not allowed in Program.body

### ISSUE THREAD

**Issue by btmills** [estree/estree#78]
After the discussions in #38 and #39, module declarations inherit directly from `Node` instead of `Declaration`. Because `Program.body` is defined as `[ Statement ]`, this has the effect of disallowing module declarations in `Program.body`.

What is the best solution? A couple possibilities:

1. Define `Program.body` to be `[ Statement | ImportDeclaration | ExportNamedDeclaration | ExportDefaultDeclaration | ExportAllDeclaration ]`, and add a note saying module declarations are only valid when `sourceType` is `"module"`.
1. Create an abstract `ModuleDeclaration` type from which module declarations inherit, and define `Program.body` to be `[ Statement | ModuleDeclaration ]`, adding a note saying `ModuleDeclaration` is only valid when `sourceType` is `"module"`.
1. Something else entirely?

I'm happy to put together a PR after a decision is made.

**Comment by michaelficarra** [comment]
Are there notes about conditions of validity anywhere else in the spec? I'm for option 2 without the special note.

**Comment by btmills** [comment]
> Are there notes about conditions of validity anywhere else in the spec?

- [`TryStatement`](https://github.com/estree/estree/blob/master/spec.md#trystatement) has "If `handler` is `null` then `finalizer` must be a `BlockStatement`."
- [`ExportNamedDeclaration`](https://github.com/estree/estree/blob/master/es6.md#exportnameddeclaration) says "Having `declaration` populated with non-empty `specifiers` or non-null `source` results in an invalid state."

The note is certainly optional, but there is precedent if having it is desirable.

**Comment by nzakas** [comment]
+1 for option 2

**Comment by michaelficarra** [comment]
@btmills: At the same time, there are many others that say nothing about validity: VariableDeclaration `declarations` must be non-empty, SequenceExpression `expressions` must have 2 or more elements, UnaryExpression `prefix` must only be `true` when `operator` is `--` or `++`, and *countless others*. Is this really the path this spec wants to go down?

**Comment by btmills** [comment]
I went ahead and implemented option 2 without the note in #79.
