### ISSUE TITLE
Thoughts about ObjectPattern (considering ES7)

### ISSUE THREAD

**Issue by fkling** [estree/estree#8]
The nodes that are accepted by `ObjectPattern` as `properties` are currently rather loosely defined (no `type`):

```webidl
interface ObjectPattern <: Pattern {
    type: "ObjectPattern";
    properties: [ { key: Literal | Identifier, value: Pattern } ];
}
```

An advantage is that `Property` nodes can be reused here (and in fact, that's what esprima and acorn are doing). However, if the [ES7 object property spread proposal](https://github.com/sebmarkbage/ecmascript-rest-spread), gets accepted, `ObjectPattern` (and `ObjectExpression`) has to be updated to allow this new node. [esprima-fb currently uses `SpreadProperty`](http://felix-kling.de/esprima_ast_explorer/#/WakULjmHFs).

As soon as different kinds of nodes are allowed, it will be necessary to distinguish between them. This can be done by checking which properties the AST node has. However, since most parsers use `Property` inside patterns, tools may just check whether the node is a `Property`, in which case they would make themselves dependent on how that specific parser represents `properties` inside patterns.

It may be useful to define the nodes that are allowed inside `properties` more strictly.

**Comment by RReverser** [comment]
Related: #23

**Comment by benjamn** [comment]
I'm 100% in favor of making `Property` a named node type.

If we're adopting `SpreadElement` and `RestElement <: Pattern` for functions and arrays (#3, #37), should we consider `SpreadProperty` and `RestProperty <: Pattern` for objects?

**Comment by RReverser** [comment]
@benjamn #23 is already merged, which made `Property` a named node type (as it is in Esprima and Acorn).

As for `SpreadProperty` and `RestProperty`, those are experimental features that will possibly come in ES7, so I guess they deserve separate discussion.
