### ISSUE TITLE
Allow literal as method names in MethodDefinition.

### ISSUE THREAD

**Issue by tuchida** [estree/estree#81]
https://github.com/estree/estree/blob/master/es6.md#methoddefinition
>     key: Identifier;

`MethodDefinition`'s key is `Identifier`.

However, in the specification has become a `PropertyName`.
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions

Therefore, it is possible to use NumericLiteral and StringLiteral.
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Foo%20{%0A%20%20123%28%29%20{%0A%20%20}%0A%20%20%0A%20%20%27abc%27%28%29%20{%0A%20%20}%0A}

**Comment by michaelficarra** [comment]
Also, computed property names. Looks like it should allow any expression.

**Comment by RReverser** [comment]
@michaelficarra Yeah, makes sense.

@tuchida Could you please send PR?

**Comment by tuchida** [comment]
@michaelficarra @RReverser Thanks! I sent. https://github.com/estree/estree/pull/83
