### ISSUE TITLE
Support new.target

### ISSUE THREAD

**Issue by jorendorff** [estree/estree#86]
Apologies if this is already in the spec; I didn't see it anywhere. Mozilla is implementing this now; the current patch converts `new.target` to this:

    { type: "NewTargetExpression" }

https://bugzilla.mozilla.org/show_bug.cgi?id=1141865

**Comment by sebmck** [comment]
This was added in #32. It was decided to go with a more generic [MetaProperty](https://github.com/estree/estree/blob/master/es6.md#metaproperty) to cover additional ones that may be introduced in the future.
