### ISSUE TITLE
Distinguish yield vs yield*

### ISSUE THREAD

**Issue by ariya** [estree/estree#88]
Currently `YieldExpression` does not tell the difference between `yield` and `yield*`.

**Comment by ariya** [comment]
Possible solution #1:

```js
interface YieldExpression <: Expression {
    type: "YieldExpression";
    argument: Expression | null;
    delegating: boolean;
}
```

where `delegating` is set to true for `yield*`. I don't have any strong preference on the name (`delegate` is another possibility). @jeffmo believed that `delegating` or `isDelegator` would be a suitable candidate.

**Comment by ariya** [comment]
Possible solution 2: have another node type, e.g. `YieldGeneratorExpression`. This will however present a compatibility issue with parsers which already implement `YieldExpression` only.

**Comment by sebmck** [comment]
[`acorn` uses `delegate`](https://github.com/marijnh/acorn/blob/71715fb7d088c7a27decd1df6c26aef103e21268/src/expression.js#L652), so does [`esprima-fb`](https://github.com/facebook/esprima/blob/fb-harmony/esprima.js#L2765). and so did [`esprima` harmony](https://github.com/jquery/esprima/blob/edebcb7ae287ca014d4926035c552ddf8f902edd/esprima.js#L2289). Makes sense to keep it.

**Comment by hzoo** [comment]
`delegate` sounds good - are there a lot of times `isX` or `x-ing` is used?

**Comment by sebmck** [comment]
[`espree` also uses `delegate`](https://github.com/eslint/espree/blob/037f1bf2ba9953a76644e04943e5d7107496f0c7/lib/ast-node-factory.js#L791).

**Comment by ariya** [comment]
Sounds like we'll stick with `delegate`. @jeffmo What do you think?

**Comment by jeffmo** [comment]
Sounds like everyone's in agreement -- so works for me!

**Comment by RReverser** [comment]
+1 to `delegate` as already-working solution.
