### ISSUE TITLE
Acorn: ImportBatchSpecifier vs Esprima: ImportNamespaceSpecifier

### ISSUE THREAD

**Issue by sebmck** [estree/estree#9]
Related

 - marijnh/acorn#157
 - benjamn/ast-types#74
 - jquery/esprima#287
 - eslint/espree#43

/cc @RReverser @caridy @impinball

**Comment by impinball** [comment]
I have little opinion in this regard, as long as there is some consistency. I'm also dragging in the naming for `export *` for node names. Here's what I see ATM:

Esprima:

- ImportNamespaceSpecifier: you're literally importing a namespace containing every named export from that module.
- ExportBatchSpecifier: you're just re-exporting everything from another module as if it was from the current module. It's like a batch export.

Acorn:

- ImportBatchSpecifier: you are batch importing all of the named exports from a module. Also, it's consistent with ExportBatchSpecifier for the exporting counterpart.
- ExportBatchSpecifier: same as in Esprima.

I personally am relatively neutral on naming, and most of my opinions are about the actual fields of the node interface itself, relevant for a different bikeshedding discussion (IMO, all imports should conform to the same base interface, but with specific default values - faster, simpler, more consistent handling for most users and languages, including statically typed ones).

**Comment by caridy** [comment]
`ImportNamespaceSpecifier` is on me :). Esprima was using `ExportBatchSpecifier` for `export * from "foo"`, but it has nothing to do with `import * as foo from "foo"`, only that they both use the `*` character, at some point we decided to use `ImportNamespaceSpecifier`, which is how is it described in the spec. I will be ok with any change in this regard.

**Comment by impinball** [comment]
@all This isn't the only problem with this node. They also have different field names, `.id` and `.name` for Esprima and Acorn, respectively. I filed #12 to address this separately. PTAL.

**Comment by RReverser** [comment]
I'm also tired of this bike-shedding as what I didn't like originally is that Esprima invented node type instead of referring to and reusing existing implementation, but now that we have centralized repo for standardization and reference, this problem should be gone. So I'll be ok with changing Acorn's type as well.

**Comment by mikesherov** [comment]
@RReverser, considering Esprima is using names the spec is referring to, I'd like to see Acorn change here. Thoughts?

**Comment by mikesherov** [comment]
Oops, sounds like #35 already makes this decision! Thanks again everyone!
