### ISSUE TITLE
Semicolon ClassElement not represented in ClassBody.body

### ISSUE THREAD

**Issue by btmills** [estree/estree#93]
![screenshot 2015-06-19 09 52 21](https://cloud.githubusercontent.com/assets/1709537/8261270/07b00c3e-1697-11e5-81a4-7f851364442d.png)

A *ClassElement* may be either a *MethodDefinition*, a **`static`** *MethodDefinition*, or a `;`, but ESTree currently only allows `MethodDefinition`s within `ClassBody.body`, which only accounts for the first two cases.

ESLint would like to prohibit unnecessary semicolons within class bodies (see eslint/eslint#2794). Is there a way to represent the semicolon within the AST?

**Comment by getify** [comment]
If it's a non-required syntactic element that a parser would typically discard (just like unnecessary whitespace or `( )` pairs), sounds to me like it's in the same boat as many other things of late: it's "concrete syntax" and should be handled as such (#41) for the tree.

**Comment by sebmck** [comment]
It has no semantic meaning so is only appropriate for a CST.

On Friday, 19 June 2015, Brandon Mills <notifications@github.com> wrote:

> [image: screenshot 2015-06-19 09 52 21]
> <https://cloud.githubusercontent.com/assets/1709537/8261270/07b00c3e-1697-11e5-81a4-7f851364442d.png>
>
> A *ClassElement* may be either a *MethodDefinition*, a *static*
> *MethodDefinition*, or a ;, but ESTree currently only allows
> MethodDefinitions within ClassBody.body, which only accounts for the
> first two cases.
>
> ESLint would like to prohibit unnecessary semicolons within class bodies
> (see eslint/eslint#2794 <https://github.com/eslint/eslint/issues/2794>).
> Is there a way to represent the semicolon within the AST?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/93>.
>


-- 
Sebastian McKenzie

**Comment by btmills** [comment]
That makes total sense; thank you both for confirming. Closing.

**Comment by getify** [comment]
I don't think it's a "no", but a "not yet". I think it's yet another vote/use-case in favor of CST.

**Comment by nzakas** [comment]
Are we sure about this? There is an `EmptyStatement` node that represents this:

```
;
```

How is this different?

**Comment by sebmck** [comment]
An `EmptyStatement` can effect the semantics of the program via completion records.

**Comment by michaelficarra** [comment]
An empty statement is also necessary for programs like `if(0);`. You can't leave that semicolon out. The IfStatement *requires* a statement.

**Comment by impinball** [comment]
True, but it's pretty distinctive (and already is signified in that specific case). I got this out of Acorn:

```json
{
  "start": 0,
  "body": [
    {
      "start": 0,
      "test": {
        "start": 3,
        "value": 0,
        "raw": "0",
        "type": "Literal",
        "end": 4
      },
      "consequent": {
        "start": 5,
        "type": "EmptyStatement",
        "end": 6
      },
      "alternate": null,
      "type": "IfStatement",
      "end": 6
    }
  ],
  "type": "Program",
  "end": 7
}
```

**Comment by nzakas** [comment]
Cool, thanks for the explanation.
