### ISSUE TITLE
How to handle comments?

### ISSUE THREAD

**Issue by donaldpipowitch** [estree/estree#94]
It looks many parsers differ in how they handle comments. It would be great if this could be fixed. See https://github.com/jquery/esprima/issues/1117 for an example. I think it isn o solution to duplicate comments that way.

**Comment by sebmck** [comment]
Related: #41

**Comment by RReverser** [comment]
There is already issue that covers this: #41

**Comment by donaldpipowitch** [comment]
Thanks.

**Comment by chilloutman** [comment]
I think this is worth discussing separately. The concrete AST involves much more than simply adding nodes of type `Comment`, which IMO would be very useful in generating comments.

A `Comment` node would not cover all possible locations where comments can be inserted, such as in `function /*comment*/ () { }`. However, for many use cases it does not need to. For JavaScript tooling to generate comments, one generally only needs leading and trailing comments.
