### ISSUE TITLE
Table of Contents?

### ISSUE THREAD

**Issue by mariusschulz** [estree/estree#96]
I find myself scrolling through `spec.md` a lot these days. What do you think about a table of contents linking to the sub-headings? I'd be happy to add one for both `spec.md` and `es6.md`.

**Comment by anko** [comment]
[*mdast-toc*](https://github.com/wooorm/mdast-toc)?

**Comment by chocolateboy** [comment]
I use this: https://github.com/thlorenz/doctoc

There's also this: https://github.com/ekalinin/github-markdown-toc

**Comment by RReverser** [comment]
Let's just build it manually, this is definitely faster and we don't add new interfaces that often to setup some complex automatic system :)

**Comment by chocolateboy** [comment]
> npm install -g doctoc
> doctoc *.md

I wouldn't exactly call it complex :-)

**Comment by RReverser** [comment]
Sure, I rather called this option manual :D Thought you're talking about setting up some hooks or something (which is possible, but needs extra effort).

**Comment by RReverser** [comment]
Looks good to me.

**Comment by chocolateboy** [comment]
:+1:

**Comment by RReverser** [comment]
@chocolateboy Thanks for telling about doctoc!

I've restructured *.md specs by grouping common structures for easier navigation. Please take a look and let me know whether it became better or worse.

**Comment by chocolateboy** [comment]
Looks better to me :sunglasses:

**Comment by hzoo** [comment]
Looks great!

**Comment by RReverser** [comment]
And now moved clauses and operators into the corresponding statements/expressions so that they are faster to find. I guess nothing more to change for now.
