### ISSUE TITLE
TemplateElement.value: spec bug?

### ISSUE THREAD

**Issue by RReverser** [estree/estree#97]
In spec, we define `TemplateElement` as following:

```typescript
interface TemplateElement <: Node {
    type: "TemplateElement";
    tail: boolean;
    value: {
        cooked: string;
        value: string;
    };
}
```

While both Acorn and Esprima use `value: { cooked, raw }` and not `value: { cooked, value }`.

I guess it's a spec bug then?

Is anyone already relying on this or can we still safely change to reflect parsers behavior?

**Comment by nzakas** [comment]
Looks like a bug - definitely not relying on it here.

**Comment by RReverser** [comment]
@nzakas Thanks for a quick response!

Ping @dherman, @ariya.

**Comment by mikesherov** [comment]
Same. Spec bug.

**Comment by sebmck** [comment]
I'm using it.

**Comment by RReverser** [comment]
@sebmck The one in spec? Is it something easy to change? (don't really want to end up with breaking all parsers)

**Comment by RReverser** [comment]
@sebmck I guess even in the worst case (if there're people relying on the bug), you can change Babel's internals to use correct field names and provide getter/setter on old name for backward compatibility.

**Comment by sebmck** [comment]
Babel uses `raw`. Is nobody in favor of just changing the spec? This was a mistake I made in #25.

**Comment by RReverser** [comment]
Ah :) That's exactly what I'm proposing, so I misunderstood your answer "I'm using it" to question "Is anyone already relying on this bug?".

Cool then, looks like everyone uses the correct format, I'll change it.

**Comment by sebmck** [comment]
Ah right sorry, misunderstood. Thought you were proposing changing implementations. :+1: from me then :blush:

**Comment by RReverser** [comment]
> Thought you were proposing changing implementations.

I'm crazy but not that much :smile_cat: 

Thanks everyone for quick feedback!
